// Generated by `cargo run -p dioxus-compose --bin codegen`. DO NOT EDIT.

package dioxus.compose.protocol

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets

enum class WidgetKind { Column, Row, Box, Text, TextField, Button, Spacer, LazyColumn, ScrollColumn, Image, Icon, Checkbox, RadioButton, Switch, Slider, ProgressIndicator, Divider, Card, Surface, Dialog, Menu, Tabs, TopAppBar, LazyRow, Tooltip, Canvas, DatePicker, TimePicker, Dropdown, Navigation, NavigationItem, Sheet, LinearProgressIndicator }

enum class PropertyKind { Text, Placeholder, Enabled, Multiline, OnClick, OnValueChange, OnSubmit, OnFocusLost, OnKeyDown, ItemCount, ItemKey, OnRangeRequested, TypeRole, FontSize, FontWeight, LineHeight, LetterSpacing, Color, TextAlign, MaxLines, Overflow, Arrangement, Spacing, SpaceRole, Alignment, Variant, Asset, Checked, Steps, Determinate, Circular, Vertical, Open, OnDismiss, SelectedIndex, Commands, Value, Min, Max, Icon, Progress }

enum class Key { Enter }

enum class WindowSizeClass { Compact, Medium, Expanded }

enum class ColorRole { Primary, OnPrimary, Secondary, OnSecondary, Surface, OnSurface, SurfaceVariant, OnSurfaceVariant, Background, OnBackground, Outline, OutlineVariant, Error, OnError, SurfaceContainer, Tertiary, OnTertiary, PrimaryContainer, OnPrimaryContainer, SecondaryContainer, OnSecondaryContainer, TertiaryContainer, OnTertiaryContainer }

enum class TypeRole { Display, Headline, Title, Subtitle, Body, BodyStrong, Label, Caption, Mono }

enum class ShapeRole { None, ExtraSmall, Small, Medium, Large, Full }

enum class SpaceRole { None, Xs, Sm, Md, Lg, Xl, Xxl }

enum class TextAlign { Start, Center, End, Justify }

enum class TextOverflow { Clip, Ellipsis, Visible }

enum class Arrangement { Start, Center, End, SpaceBetween, SpaceAround, SpaceEvenly }

enum class Alignment { TopStart, TopCenter, TopEnd, CenterStart, Center, CenterEnd, BottomStart, BottomCenter, BottomEnd }

enum class ButtonVariant { Filled, Tonal, Outlined, Text }

enum class DesignSystem { Material3, Cupertino, Fluent, Gnome, Breeze, Deepin }

enum class ColorScheme { Light, Dark, FollowSystem }

enum class AssetKind { Png, Jpeg, Svg, VectorIcon }

enum class IconRole { Back, Forward, Close, Search, Add, Check, Settings, More, Home, List, Inbox }

enum class MessageDuration { Short, Long }

enum class LoopMode(val wire: Byte) {
    /** The Renderer runs the loop and the Host blocks inside it. Desktop. */
    Renderer(0),

    /** The platform owns the process and the loop. Android, iOS and the web. */
    Platform(1),
}

sealed interface Paint {
    data class Role(val role: ColorRole) : Paint

    /** A literal 0xAARRGGBB colour. */
    data class Literal(val argb: Int) : Paint
}

data class Theme(
    val designSystem: DesignSystem,
    val fallback: DesignSystem,
    val colorScheme: ColorScheme,
    val adaptive: Boolean,
)

sealed interface PropertyValue {
    data object None : PropertyValue
    data class Text(val value: String) : PropertyValue
    data class Bool(val value: Boolean) : PropertyValue
    data class Integer(val value: Long) : PropertyValue
    data class Float(val value: kotlin.Float) : PropertyValue
    class Bytes(val value: ByteArray) : PropertyValue
}

/**
 * One drawing command. Coordinates are dp from the Canvas's top-left corner.
 *
 * Colour is a [Paint], so a command may name a ColorRole and the design system
 * decides what it looks like.
 */
sealed interface DrawCommand {
    val paint: Paint

    data class Line(override val paint: Paint, val x1: kotlin.Float, val y1: kotlin.Float, val x2: kotlin.Float, val y2: kotlin.Float, val strokeWidth: kotlin.Float) : DrawCommand
    data class Rect(override val paint: Paint, val x: kotlin.Float, val y: kotlin.Float, val width: kotlin.Float, val height: kotlin.Float, val strokeWidth: kotlin.Float) : DrawCommand
    data class RoundRect(override val paint: Paint, val x: kotlin.Float, val y: kotlin.Float, val width: kotlin.Float, val height: kotlin.Float, val radius: kotlin.Float, val strokeWidth: kotlin.Float) : DrawCommand
    data class Circle(override val paint: Paint, val centerX: kotlin.Float, val centerY: kotlin.Float, val radius: kotlin.Float, val strokeWidth: kotlin.Float) : DrawCommand
    data class Arc(override val paint: Paint, val centerX: kotlin.Float, val centerY: kotlin.Float, val radius: kotlin.Float, val startDegrees: kotlin.Float, val sweepDegrees: kotlin.Float, val strokeWidth: kotlin.Float) : DrawCommand
    data class PolylineRef(override val paint: Paint, val assetId: Int, val strokeWidth: kotlin.Float) : DrawCommand
    data class TextAt(override val paint: Paint, val textOffset: Int, val textLength: Int, val x: kotlin.Float, val y: kotlin.Float, val typeRole: TypeRole) : DrawCommand
}

/** Decodes a Canvas command list: fixed-size records, then the TextAt strings. */
object DrawCommands {
    const val COMMAND_LENGTH = 36

    fun decode(bytes: ByteArray): List<DrawCommand> {
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        val commands = ArrayList<DrawCommand>(bytes.size / COMMAND_LENGTH)
        var offset = 0
        while (offset + COMMAND_LENGTH <= bytes.size) {
            val tag = buffer.getShort(offset).toInt() and 0xffff
            val length = buffer.getShort(offset + 2).toInt() and 0xffff
            // The text region starts where the records stop decoding, so an unreadable
            // record ends the list rather than failing the whole batch.
            if (length != COMMAND_LENGTH) break
            val paintBits = buffer.getLong(offset + 4)
            val kind = (paintBits ushr 32).toInt()
            if (kind != 1 && kind != 2) break
            val paint = if (kind == 1) {
                Paint.Role(colorRoleOrNull(paintBits.toInt()) ?: break)
            } else {
                Paint.Literal(paintBits.toInt())
            }
            fun word(index: Int): Int = buffer.getInt(offset + 12 + index * 4)
            fun real(index: Int): kotlin.Float = kotlin.Float.fromBits(word(index))
            val command = when (tag) {
                1 -> DrawCommand.Line(paint, real(0), real(1), real(2), real(3), real(4))
                2 -> DrawCommand.Rect(paint, real(0), real(1), real(2), real(3), real(4))
                3 -> DrawCommand.RoundRect(paint, real(0), real(1), real(2), real(3), real(4), real(5))
                4 -> DrawCommand.Circle(paint, real(0), real(1), real(2), real(3))
                5 -> DrawCommand.Arc(paint, real(0), real(1), real(2), real(3), real(4), real(5))
                6 -> DrawCommand.PolylineRef(paint, word(0), real(1))
                7 -> DrawCommand.TextAt(paint, word(0), word(1), real(2), real(3), typeRoleOrNull(word(4)) ?: break)
                else -> break
            }
            commands.add(command)
            offset += COMMAND_LENGTH
        }
        return commands
    }

    /** The string a TextAt points at, measured from the start of the list. */
    fun textOf(bytes: ByteArray, command: DrawCommand.TextAt): String {
        val end = command.textOffset.toLong() + command.textLength.toLong()
        if (command.textOffset < 0 || command.textLength < 0 || end > bytes.size.toLong()) {
            return ""
        }
        return String(bytes, command.textOffset, command.textLength, StandardCharsets.UTF_8)
    }

    private fun typeRoleOrNull(tag: Int): TypeRole? = when (tag) {
        1 -> TypeRole.Display
        2 -> TypeRole.Headline
        3 -> TypeRole.Title
        4 -> TypeRole.Subtitle
        5 -> TypeRole.Body
        6 -> TypeRole.BodyStrong
        7 -> TypeRole.Label
        8 -> TypeRole.Caption
        9 -> TypeRole.Mono
        else -> null
    }

    private fun colorRoleOrNull(tag: Int): ColorRole? = when (tag) {
        1 -> ColorRole.Primary
        2 -> ColorRole.OnPrimary
        3 -> ColorRole.Secondary
        4 -> ColorRole.OnSecondary
        5 -> ColorRole.Surface
        6 -> ColorRole.OnSurface
        7 -> ColorRole.SurfaceVariant
        8 -> ColorRole.OnSurfaceVariant
        9 -> ColorRole.Background
        10 -> ColorRole.OnBackground
        11 -> ColorRole.Outline
        12 -> ColorRole.OutlineVariant
        13 -> ColorRole.Error
        14 -> ColorRole.OnError
        15 -> ColorRole.SurfaceContainer
        16 -> ColorRole.Tertiary
        17 -> ColorRole.OnTertiary
        18 -> ColorRole.PrimaryContainer
        19 -> ColorRole.OnPrimaryContainer
        20 -> ColorRole.SecondaryContainer
        21 -> ColorRole.OnSecondaryContainer
        22 -> ColorRole.TertiaryContainer
        23 -> ColorRole.OnTertiaryContainer
        else -> null
    }

}

sealed interface Modifier {
    data object Empty : Modifier
    data class Padding(val value: kotlin.Float) : Modifier
    data object FillMaxWidth : Modifier
    data object FillMaxHeight : Modifier
    data class Width(val value: kotlin.Float) : Modifier
    data class Height(val value: kotlin.Float) : Modifier
    data class Size(val width: kotlin.Float, val height: kotlin.Float) : Modifier
    data class Background(val paint: Paint) : Modifier
    data class Clickable(val handlerId: Long) : Modifier
    data class PaddingRole(val role: dioxus.compose.protocol.SpaceRole) : Modifier
    data class PaddingEach(val start: kotlin.Float, val top: kotlin.Float, val end: kotlin.Float, val bottom: kotlin.Float) : Modifier
    data class Weight(val value: kotlin.Float) : Modifier
    data class Shape(val topStart: kotlin.Float, val topEnd: kotlin.Float, val bottomEnd: kotlin.Float, val bottomStart: kotlin.Float) : Modifier
    data class ShapeRole(val role: dioxus.compose.protocol.ShapeRole) : Modifier
    data class Border(val width: kotlin.Float, val paint: Paint) : Modifier
    data class Elevation(val value: kotlin.Float) : Modifier
}

sealed interface Mutation {
    data class Create(val nodeId: Int, val widget: WidgetKind) : Mutation
    data class SetProp(val nodeId: Int, val property: PropertyKind, val value: PropertyValue) : Mutation
    data class SetModifier(val nodeId: Int, val index: Int, val modifier: Modifier) : Mutation
    data class Insert(val parentId: Int, val nodeId: Int, val index: Int) : Mutation
    data class Move(val parentId: Int, val nodeId: Int, val index: Int) : Mutation
    data class Remove(val nodeId: Int) : Mutation
    data class SetText(val nodeId: Int, val text: String, val selectionStart: Int, val selectionEnd: Int) : Mutation
    data class AppendText(val nodeId: Int, val text: String) : Mutation
    data class SetTheme(val theme: Theme) : Mutation

    /**
     * The bytes of one asset. `kind` is the raw wire tag rather than an [AssetKind],
     * because a kind this Renderer cannot read has to be reported as a protocol error by
     * the asset cache instead of stopping the rest of the batch from being applied.
     *
     * `bytes` is already a copy: the batch buffer is only valid for the call that carried
     * it, and an asset has to outlive the frame that draws it.
     */
    data class RegisterAsset(val assetId: Int, val kind: Int, val bytes: ByteArray) : Mutation {
        override fun equals(other: Any?): Boolean =
            this === other ||
                (other is RegisterAsset && assetId == other.assetId && kind == other.kind &&
                    bytes.contentEquals(other.bytes))

        override fun hashCode(): Int =
            (assetId * 31 + kind) * 31 + bytes.contentHashCode()
    }

    data class ReleaseAsset(val assetId: Int) : Mutation

    /**
     * One sentence to say to the user, with an optional thing to do about it.
     *
     * It names no node because it is not in the tree. The Host says it once; how long it
     * stays, where it sits and what happens when a second one arrives while the first is
     * still up are the Renderer's to decide.
     *
     * `handlerId` is 0 when the message has no action, and `action` is then empty.
     */
    data class ShowMessage(
        val handlerId: Long,
        val text: String,
        val action: String,
        val duration: MessageDuration,
    ) : Mutation
}

sealed interface HostEvent {
    val nodeId: Int
    val handlerId: Long

    data class Clicked(override val nodeId: Int, override val handlerId: Long) : HostEvent
    data class TextChanged(override val nodeId: Int, override val handlerId: Long, val text: String) : HostEvent
    data class TextSubmitted(override val nodeId: Int, override val handlerId: Long, val text: String) : HostEvent
    data class FocusLost(override val nodeId: Int, override val handlerId: Long) : HostEvent
    data class ProtocolError(override val nodeId: Int, override val handlerId: Long, val code: Int, val message: String) : HostEvent
    data class KeyDown(override val nodeId: Int, override val handlerId: Long, val key: Key, val shiftKey: Boolean, val ctrlKey: Boolean, val altKey: Boolean, val metaKey: Boolean) : HostEvent
    data class RangeRequested(override val nodeId: Int, override val handlerId: Long, val start: Int, val count: Int) : HostEvent
    data class ValueChanged(override val nodeId: Int, override val handlerId: Long, val value: Double) : HostEvent
    data class WindowSizeChanged(override val nodeId: Int, override val handlerId: Long, val widthDp: kotlin.Float, val heightDp: kotlin.Float, val sizeClass: WindowSizeClass) : HostEvent
    data class Resync(override val nodeId: Int, override val handlerId: Long) : HostEvent
    data class LifecycleStart(override val nodeId: Int, override val handlerId: Long) : HostEvent
    data class LifecycleStop(override val nodeId: Int, override val handlerId: Long) : HostEvent
}

class ProtocolException(message: String, val offset: Int) :
    IllegalArgumentException("$message at byte offset $offset")

object Protocol {
    const val SCHEMA_HASH: Long = -1735345747504770763L
    const val PROTOCOL_VERSION: Int = 1

    private const val TAG_ENVELOPE = 0
    private const val TAG_CREATE = 1
    private const val TAG_SET_PROP = 2
    private const val TAG_SET_MODIFIER = 3
    private const val TAG_INSERT = 4
    private const val TAG_MOVE = 5
    private const val TAG_REMOVE = 6
    private const val TAG_SET_TEXT = 7
    private const val TAG_APPEND_TEXT = 8
    private const val TAG_SET_THEME = 9
    private const val TAG_REGISTER_ASSET = 10
    private const val TAG_RELEASE_ASSET = 11
    private const val TAG_SHOW_MESSAGE = 12
    private const val ENVELOPE_LENGTH = 12

    private const val VALUE_NONE = 0
    private const val VALUE_TEXT = 1
    private const val VALUE_BOOL = 2
    private const val VALUE_INTEGER = 3
    private const val VALUE_FLOAT = 4
    private const val VALUE_BYTES = 5

    /** Decodes a batch in place. Must not copy the buffer; only strings become Kotlin Strings. */
    fun decode(batch: ByteBuffer, onMutation: (Mutation) -> Unit) {
        val base = batch.position()
        val available = batch.remaining()
        val previousOrder = batch.order()
        batch.order(ByteOrder.LITTLE_ENDIAN)
        try {
            requireRange(available, 0, ENVELOPE_LENGTH, 0)
            if (readU16(batch, base, available, 0) != TAG_ENVELOPE ||
                readU16(batch, base, available, 2) != ENVELOPE_LENGTH
            ) {
                throw ProtocolException("invalid batch envelope", 0)
            }
            val recordsLengthLong = readU32(batch, base, available, 4)
            val countLong = readU32(batch, base, available, 8)
            if (recordsLengthLong < ENVELOPE_LENGTH ||
                recordsLengthLong > available.toLong() ||
                recordsLengthLong % 4L != 0L
            ) {
                throw ProtocolException("invalid records length", 4)
            }
            if (countLong > Int.MAX_VALUE.toLong()) {
                throw ProtocolException("record count is too large", 8)
            }
            val recordsLength = recordsLengthLong.toInt()
            val count = countLong.toInt()
            var offset = ENVELOPE_LENGTH
            var decoded = 0
            while (offset < recordsLength) {
                requireRange(recordsLength, offset, 4, offset)
                val tag = readU16(batch, base, available, offset)
                val length = readU16(batch, base, available, offset + 2)
                if (length < 4 || length % 4 != 0 || offset.toLong() + length > recordsLength) {
                    throw ProtocolException("invalid record length", offset + 2)
                }
                val mutation = when (tag) {
                    TAG_CREATE -> {
                        requireRecordLength(length, 12, offset)
                        Mutation.Create(
                            readU32(batch, base, available, offset + 4).toInt(),
                            widgetKind(readU16(batch, base, available, offset + 8), offset + 8),
                        )
                    }
                    TAG_SET_PROP -> {
                        requireRecordLength(length, 24, offset)
                        val value = when (val valueKind = readU16(batch, base, available, offset + 10)) {
                            VALUE_NONE -> PropertyValue.None
                            VALUE_TEXT -> PropertyValue.Text(readString(batch, base, available, offset + 12))
                            VALUE_BOOL -> PropertyValue.Bool(readU64(batch, base, available, offset + 12) != 0L)
                            VALUE_INTEGER -> PropertyValue.Integer(readU64(batch, base, available, offset + 12))
                            VALUE_FLOAT -> PropertyValue.Float(
                                kotlin.Float.fromBits(readU64(batch, base, available, offset + 12).toInt()),
                            )
                            VALUE_BYTES -> PropertyValue.Bytes(readBytes(batch, base, available, offset + 12))
                            else -> throw ProtocolException("unknown property value tag $valueKind", offset + 10)
                        }
                        Mutation.SetProp(
                            readU32(batch, base, available, offset + 4).toInt(),
                            propertyKind(readU16(batch, base, available, offset + 8), offset + 8),
                            value,
                        )
                    }
                    TAG_SET_MODIFIER -> {
                        requireRecordLength(length, 28, offset)
                        Mutation.SetModifier(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU16(batch, base, available, offset + 8),
                            modifier(
                                readU16(batch, base, available, offset + 10),
                                readU64(batch, base, available, offset + 12),
                                readU64(batch, base, available, offset + 20),
                                offset + 10,
                            ),
                        )
                    }
                    TAG_INSERT -> {
                        requireRecordLength(length, 16, offset)
                        Mutation.Insert(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU32(batch, base, available, offset + 8).toInt(),
                            readU32(batch, base, available, offset + 12).toInt(),
                        )
                    }
                    TAG_MOVE -> {
                        requireRecordLength(length, 16, offset)
                        Mutation.Move(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU32(batch, base, available, offset + 8).toInt(),
                            readU32(batch, base, available, offset + 12).toInt(),
                        )
                    }
                    TAG_REMOVE -> {
                        requireRecordLength(length, 8, offset)
                        Mutation.Remove(readU32(batch, base, available, offset + 4).toInt())
                    }
                    TAG_SET_TEXT -> {
                        requireRecordLength(length, 24, offset)
                        Mutation.SetText(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readString(batch, base, available, offset + 8),
                            readU32(batch, base, available, offset + 16).toInt(),
                            readU32(batch, base, available, offset + 20).toInt(),
                        )
                    }
                    TAG_APPEND_TEXT -> {
                        requireRecordLength(length, 16, offset)
                        Mutation.AppendText(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readString(batch, base, available, offset + 8),
                        )
                    }
                    TAG_SET_THEME -> {
                        requireRecordLength(length, 12, offset)
                        val adaptive = readU16(batch, base, available, offset + 10)
                        if (adaptive > 1) {
                            throw ProtocolException("invalid adaptive flag $adaptive", offset + 10)
                        }
                        Mutation.SetTheme(
                            Theme(
                                designSystem(readU16(batch, base, available, offset + 4), offset + 4),
                                designSystem(readU16(batch, base, available, offset + 6), offset + 6),
                                colorScheme(readU16(batch, base, available, offset + 8), offset + 8),
                                adaptive == 1,
                            ),
                        )
                    }
                    TAG_REGISTER_ASSET -> {
                        requireRecordLength(length, 20, offset)
                        Mutation.RegisterAsset(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU16(batch, base, available, offset + 8),
                            readBytes(batch, base, available, offset + 12),
                        )
                    }
                    TAG_RELEASE_ASSET -> {
                        requireRecordLength(length, 8, offset)
                        Mutation.ReleaseAsset(readU32(batch, base, available, offset + 4).toInt())
                    }
                    TAG_SHOW_MESSAGE -> {
                        requireRecordLength(length, 32, offset)
                        Mutation.ShowMessage(
                            readU64(batch, base, available, offset + 4),
                            readString(batch, base, available, offset + 12),
                            readString(batch, base, available, offset + 20),
                            messageDuration(readU16(batch, base, available, offset + 28), offset + 28),
                        )
                    }
                    else -> throw ProtocolException("unknown mutation tag $tag", offset)
                }
                onMutation(mutation)
                decoded += 1
                offset += length
            }
            if (offset != recordsLength || decoded != count) {
                throw ProtocolException("record count does not match envelope", offset)
            }
        } finally {
            batch.order(previousOrder)
        }
    }

    /** Encodes one event into `out` (little-endian), returns bytes written. */
    fun encodeEvent(event: HostEvent, out: ByteBuffer): Int {
        val start = out.position()
        val previousOrder = out.order()
        out.order(ByteOrder.LITTLE_ENDIAN)
        try {
            val text = when (event) {
                is HostEvent.Clicked -> null
                is HostEvent.TextChanged -> event.text.toByteArray(StandardCharsets.UTF_8)
                is HostEvent.TextSubmitted -> event.text.toByteArray(StandardCharsets.UTF_8)
                is HostEvent.FocusLost -> null
                is HostEvent.ProtocolError -> event.message.toByteArray(StandardCharsets.UTF_8)
                is HostEvent.KeyDown -> null
                is HostEvent.RangeRequested -> null
                is HostEvent.ValueChanged -> null
                is HostEvent.WindowSizeChanged -> null
                is HostEvent.Resync -> null
                is HostEvent.LifecycleStart -> null
                is HostEvent.LifecycleStop -> null
            }
            val recordLength = when (event) {
                is HostEvent.Clicked -> 16
                is HostEvent.TextChanged -> 24
                is HostEvent.TextSubmitted -> 24
                is HostEvent.FocusLost -> 16
                is HostEvent.ProtocolError -> 28
                is HostEvent.KeyDown -> 20
                is HostEvent.RangeRequested -> 24
                is HostEvent.ValueChanged -> 24
                is HostEvent.WindowSizeChanged -> 28
                is HostEvent.Resync -> 16
                is HostEvent.LifecycleStart -> 16
                is HostEvent.LifecycleStop -> 16
            }
            val totalLength = recordLength.toLong() + (text?.size ?: 0)
            if (totalLength > Int.MAX_VALUE || totalLength > out.remaining().toLong()) {
                throw ProtocolException("event output buffer is too small", 0)
            }
            val tag = when (event) {
                is HostEvent.Clicked -> 1
                is HostEvent.TextChanged -> 2
                is HostEvent.TextSubmitted -> 3
                is HostEvent.FocusLost -> 4
                is HostEvent.ProtocolError -> 5
                is HostEvent.KeyDown -> 6
                is HostEvent.RangeRequested -> 7
                is HostEvent.ValueChanged -> 16
                is HostEvent.WindowSizeChanged -> 17
                is HostEvent.Resync -> 18
                is HostEvent.LifecycleStart -> 19
                is HostEvent.LifecycleStop -> 20
            }
            out.putShort(tag.toShort())
            out.putShort(recordLength.toShort())
            out.putInt(event.nodeId)
            out.putLong(event.handlerId)
            when (event) {
                is HostEvent.Clicked -> Unit
                is HostEvent.TextChanged -> writeStringReference(out, recordLength, text!!)
                is HostEvent.TextSubmitted -> writeStringReference(out, recordLength, text!!)
                is HostEvent.FocusLost -> Unit
                is HostEvent.ProtocolError -> {
                    out.putInt(event.code)
                    writeStringReference(out, recordLength, text!!)
                }
                is HostEvent.KeyDown -> {
                    out.putShort(keyTag(event.key).toShort())
                    var modifiers = 0
                    if (event.shiftKey) modifiers = modifiers or 0x01
                    if (event.ctrlKey) modifiers = modifiers or 0x02
                    if (event.altKey) modifiers = modifiers or 0x04
                    if (event.metaKey) modifiers = modifiers or 0x08
                    out.put(modifiers.toByte())
                    out.put(0.toByte())
                }
                is HostEvent.RangeRequested -> {
                    out.putInt(event.start)
                    out.putInt(event.count)
                }
                is HostEvent.ValueChanged -> out.putDouble(event.value)
                is HostEvent.WindowSizeChanged -> {
                    out.putFloat(event.widthDp)
                    out.putFloat(event.heightDp)
                    out.putInt(windowSizeClassTag(event.sizeClass))
                }
                is HostEvent.Resync -> Unit
                is HostEvent.LifecycleStart -> Unit
                is HostEvent.LifecycleStop -> Unit
            }
            if (text != null) out.put(text)
            return out.position() - start
        } finally {
            out.order(previousOrder)
        }
    }

    /**
     * Handshake payload the Renderer sends to dioxus_compose_host_init.
     *
     * `loopMode` says who owns the frame loop: the Renderer on desktop, the platform on
     * Android, iOS and the web.
     */
    fun handshake(out: ByteBuffer, loopMode: LoopMode = LoopMode.Renderer): Int {
        val start = out.position()
        if (out.remaining() < 12) {
            throw ProtocolException("handshake output buffer is too small", 0)
        }
        val previousOrder = out.order()
        out.order(ByteOrder.LITTLE_ENDIAN)
        try {
            out.putLong(SCHEMA_HASH)
            out.putShort(PROTOCOL_VERSION.toShort())
            out.put(loopMode.wire)
            out.put(0.toByte()) // Reserved for alignment.
            return out.position() - start
        } finally {
            out.order(previousOrder)
        }
    }

    private fun writeStringReference(out: ByteBuffer, offset: Int, bytes: ByteArray) {
        out.putInt(offset)
        out.putInt(bytes.size)
    }

    private fun widgetKind(tag: Int, offset: Int): WidgetKind = when (tag) {
        1 -> WidgetKind.Column
        2 -> WidgetKind.Row
        3 -> WidgetKind.Box
        4 -> WidgetKind.Text
        5 -> WidgetKind.TextField
        6 -> WidgetKind.Button
        7 -> WidgetKind.Spacer
        8 -> WidgetKind.LazyColumn
        9 -> WidgetKind.ScrollColumn
        10 -> WidgetKind.Image
        11 -> WidgetKind.Icon
        12 -> WidgetKind.Checkbox
        13 -> WidgetKind.RadioButton
        14 -> WidgetKind.Switch
        15 -> WidgetKind.Slider
        16 -> WidgetKind.ProgressIndicator
        17 -> WidgetKind.Divider
        18 -> WidgetKind.Card
        19 -> WidgetKind.Surface
        20 -> WidgetKind.Dialog
        21 -> WidgetKind.Menu
        22 -> WidgetKind.Tabs
        23 -> WidgetKind.TopAppBar
        24 -> WidgetKind.LazyRow
        25 -> WidgetKind.Tooltip
        26 -> WidgetKind.Canvas
        27 -> WidgetKind.DatePicker
        28 -> WidgetKind.TimePicker
        29 -> WidgetKind.Dropdown
        30 -> WidgetKind.Navigation
        31 -> WidgetKind.NavigationItem
        32 -> WidgetKind.Sheet
        100 -> WidgetKind.LinearProgressIndicator
        else -> throw ProtocolException("unknown widget tag $tag", offset)
    }

    private fun propertyKind(tag: Int, offset: Int): PropertyKind = when (tag) {
        1 -> PropertyKind.Text
        2 -> PropertyKind.Placeholder
        3 -> PropertyKind.Enabled
        4 -> PropertyKind.Multiline
        5 -> PropertyKind.OnClick
        6 -> PropertyKind.OnValueChange
        7 -> PropertyKind.OnSubmit
        8 -> PropertyKind.OnFocusLost
        9 -> PropertyKind.OnKeyDown
        10 -> PropertyKind.ItemCount
        11 -> PropertyKind.ItemKey
        12 -> PropertyKind.OnRangeRequested
        13 -> PropertyKind.TypeRole
        14 -> PropertyKind.FontSize
        15 -> PropertyKind.FontWeight
        16 -> PropertyKind.LineHeight
        17 -> PropertyKind.LetterSpacing
        18 -> PropertyKind.Color
        19 -> PropertyKind.TextAlign
        20 -> PropertyKind.MaxLines
        21 -> PropertyKind.Overflow
        22 -> PropertyKind.Arrangement
        23 -> PropertyKind.Spacing
        24 -> PropertyKind.SpaceRole
        25 -> PropertyKind.Alignment
        26 -> PropertyKind.Variant
        28 -> PropertyKind.Asset
        32 -> PropertyKind.Checked
        33 -> PropertyKind.Steps
        34 -> PropertyKind.Determinate
        35 -> PropertyKind.Circular
        36 -> PropertyKind.Vertical
        40 -> PropertyKind.Open
        41 -> PropertyKind.OnDismiss
        42 -> PropertyKind.SelectedIndex
        50 -> PropertyKind.Commands
        51 -> PropertyKind.Value
        52 -> PropertyKind.Min
        53 -> PropertyKind.Max
        60 -> PropertyKind.Icon
        27 -> PropertyKind.Progress
        else -> throw ProtocolException("unknown property tag $tag", offset)
    }

    private fun keyTag(key: Key): Int = when (key) {
        Key.Enter -> 1
    }

    private fun windowSizeClassTag(sizeClass: WindowSizeClass): Int = when (sizeClass) {
        WindowSizeClass.Compact -> 0
        WindowSizeClass.Medium -> 1
        WindowSizeClass.Expanded -> 2
    }

    private fun colorRole(tag: Int, offset: Int): ColorRole = when (tag) {
        1 -> ColorRole.Primary
        2 -> ColorRole.OnPrimary
        3 -> ColorRole.Secondary
        4 -> ColorRole.OnSecondary
        5 -> ColorRole.Surface
        6 -> ColorRole.OnSurface
        7 -> ColorRole.SurfaceVariant
        8 -> ColorRole.OnSurfaceVariant
        9 -> ColorRole.Background
        10 -> ColorRole.OnBackground
        11 -> ColorRole.Outline
        12 -> ColorRole.OutlineVariant
        13 -> ColorRole.Error
        14 -> ColorRole.OnError
        15 -> ColorRole.SurfaceContainer
        16 -> ColorRole.Tertiary
        17 -> ColorRole.OnTertiary
        18 -> ColorRole.PrimaryContainer
        19 -> ColorRole.OnPrimaryContainer
        20 -> ColorRole.SecondaryContainer
        21 -> ColorRole.OnSecondaryContainer
        22 -> ColorRole.TertiaryContainer
        23 -> ColorRole.OnTertiaryContainer
        else -> throw ProtocolException("unknown ColorRole tag $tag", offset)
    }

    private fun typeRole(tag: Int, offset: Int): TypeRole = when (tag) {
        1 -> TypeRole.Display
        2 -> TypeRole.Headline
        3 -> TypeRole.Title
        4 -> TypeRole.Subtitle
        5 -> TypeRole.Body
        6 -> TypeRole.BodyStrong
        7 -> TypeRole.Label
        8 -> TypeRole.Caption
        9 -> TypeRole.Mono
        else -> throw ProtocolException("unknown TypeRole tag $tag", offset)
    }

    private fun shapeRole(tag: Int, offset: Int): ShapeRole = when (tag) {
        1 -> ShapeRole.None
        2 -> ShapeRole.ExtraSmall
        3 -> ShapeRole.Small
        4 -> ShapeRole.Medium
        5 -> ShapeRole.Large
        6 -> ShapeRole.Full
        else -> throw ProtocolException("unknown ShapeRole tag $tag", offset)
    }

    private fun spaceRole(tag: Int, offset: Int): SpaceRole = when (tag) {
        1 -> SpaceRole.None
        2 -> SpaceRole.Xs
        3 -> SpaceRole.Sm
        4 -> SpaceRole.Md
        5 -> SpaceRole.Lg
        6 -> SpaceRole.Xl
        7 -> SpaceRole.Xxl
        else -> throw ProtocolException("unknown SpaceRole tag $tag", offset)
    }

    private fun textAlign(tag: Int, offset: Int): TextAlign = when (tag) {
        1 -> TextAlign.Start
        2 -> TextAlign.Center
        3 -> TextAlign.End
        4 -> TextAlign.Justify
        else -> throw ProtocolException("unknown TextAlign tag $tag", offset)
    }

    private fun textOverflow(tag: Int, offset: Int): TextOverflow = when (tag) {
        1 -> TextOverflow.Clip
        2 -> TextOverflow.Ellipsis
        3 -> TextOverflow.Visible
        else -> throw ProtocolException("unknown TextOverflow tag $tag", offset)
    }

    private fun arrangement(tag: Int, offset: Int): Arrangement = when (tag) {
        1 -> Arrangement.Start
        2 -> Arrangement.Center
        3 -> Arrangement.End
        4 -> Arrangement.SpaceBetween
        5 -> Arrangement.SpaceAround
        6 -> Arrangement.SpaceEvenly
        else -> throw ProtocolException("unknown Arrangement tag $tag", offset)
    }

    private fun alignment(tag: Int, offset: Int): Alignment = when (tag) {
        1 -> Alignment.TopStart
        2 -> Alignment.TopCenter
        3 -> Alignment.TopEnd
        4 -> Alignment.CenterStart
        5 -> Alignment.Center
        6 -> Alignment.CenterEnd
        7 -> Alignment.BottomStart
        8 -> Alignment.BottomCenter
        9 -> Alignment.BottomEnd
        else -> throw ProtocolException("unknown Alignment tag $tag", offset)
    }

    private fun buttonVariant(tag: Int, offset: Int): ButtonVariant = when (tag) {
        1 -> ButtonVariant.Filled
        2 -> ButtonVariant.Tonal
        3 -> ButtonVariant.Outlined
        4 -> ButtonVariant.Text
        else -> throw ProtocolException("unknown ButtonVariant tag $tag", offset)
    }

    private fun designSystem(tag: Int, offset: Int): DesignSystem = when (tag) {
        1 -> DesignSystem.Material3
        2 -> DesignSystem.Cupertino
        3 -> DesignSystem.Fluent
        4 -> DesignSystem.Gnome
        5 -> DesignSystem.Breeze
        6 -> DesignSystem.Deepin
        else -> throw ProtocolException("unknown DesignSystem tag $tag", offset)
    }

    private fun colorScheme(tag: Int, offset: Int): ColorScheme = when (tag) {
        1 -> ColorScheme.Light
        2 -> ColorScheme.Dark
        3 -> ColorScheme.FollowSystem
        else -> throw ProtocolException("unknown ColorScheme tag $tag", offset)
    }

    private fun assetKind(tag: Int, offset: Int): AssetKind = when (tag) {
        1 -> AssetKind.Png
        2 -> AssetKind.Jpeg
        3 -> AssetKind.Svg
        4 -> AssetKind.VectorIcon
        else -> throw ProtocolException("unknown AssetKind tag $tag", offset)
    }

    private fun iconRole(tag: Int, offset: Int): IconRole = when (tag) {
        1 -> IconRole.Back
        2 -> IconRole.Forward
        3 -> IconRole.Close
        4 -> IconRole.Search
        5 -> IconRole.Add
        6 -> IconRole.Check
        7 -> IconRole.Settings
        8 -> IconRole.More
        9 -> IconRole.Home
        10 -> IconRole.List
        11 -> IconRole.Inbox
        else -> throw ProtocolException("unknown IconRole tag $tag", offset)
    }

    private fun messageDuration(tag: Int, offset: Int): MessageDuration = when (tag) {
        1 -> MessageDuration.Short
        2 -> MessageDuration.Long
        else -> throw ProtocolException("unknown MessageDuration tag $tag", offset)
    }

    private fun paint(bits: Long, offset: Int): Paint {
        val value = bits.toInt()
        return when (val kind = (bits ushr 32).toInt()) {
            1 -> Paint.Role(colorRole(value, offset))
            2 -> Paint.Literal(value)
            else -> throw ProtocolException("unknown paint kind $kind", offset)
        }
    }

    private fun modifier(tag: Int, first: Long, second: Long, offset: Int): Modifier = when (tag) {
        0 -> Modifier.Empty
        1 -> Modifier.Padding(kotlin.Float.fromBits(first.toInt()))
        2 -> Modifier.FillMaxWidth
        3 -> Modifier.FillMaxHeight
        4 -> Modifier.Width(kotlin.Float.fromBits(first.toInt()))
        5 -> Modifier.Height(kotlin.Float.fromBits(first.toInt()))
        6 -> Modifier.Size(kotlin.Float.fromBits(first.toInt()), kotlin.Float.fromBits(second.toInt()))
        7 -> Modifier.Background(paint(first, offset))
        8 -> Modifier.Clickable(first)
        9 -> Modifier.PaddingRole(spaceRole(first.toInt(), offset))
        10 -> Modifier.PaddingEach(kotlin.Float.fromBits(first.toInt()), kotlin.Float.fromBits((first ushr 32).toInt()), kotlin.Float.fromBits(second.toInt()), kotlin.Float.fromBits((second ushr 32).toInt()))
        11 -> Modifier.Weight(kotlin.Float.fromBits(first.toInt()))
        12 -> Modifier.Shape(kotlin.Float.fromBits(first.toInt()), kotlin.Float.fromBits((first ushr 32).toInt()), kotlin.Float.fromBits(second.toInt()), kotlin.Float.fromBits((second ushr 32).toInt()))
        13 -> Modifier.ShapeRole(shapeRole(first.toInt(), offset))
        14 -> Modifier.Border(kotlin.Float.fromBits(first.toInt()), paint(second, offset))
        15 -> Modifier.Elevation(kotlin.Float.fromBits(first.toInt()))
        else -> throw ProtocolException("unknown modifier tag $tag", offset)
    }

    /**
     * An arena range with no UTF-8 requirement, used by both a drawing command list and an
     * asset's bytes. For an asset this is the one copy this side makes, and it happens at
     * registration rather than per frame.
     */
    private fun readBytes(batch: ByteBuffer, base: Int, available: Int, referenceOffset: Int): ByteArray {
        val offsetLong = readU32(batch, base, available, referenceOffset)
        val lengthLong = readU32(batch, base, available, referenceOffset + 4)
        if (offsetLong > Int.MAX_VALUE || lengthLong > Int.MAX_VALUE) {
            throw ProtocolException("byte range is too large", referenceOffset)
        }
        val offset = offsetLong.toInt()
        val length = lengthLong.toInt()
        requireRange(available, offset, length, referenceOffset)
        val copy = ByteArray(length)
        val view = batch.duplicate()
        view.position(base + offset)
        view.get(copy)
        return copy
    }

    private fun readString(batch: ByteBuffer, base: Int, available: Int, referenceOffset: Int): String {
        val offsetLong = readU32(batch, base, available, referenceOffset)
        val lengthLong = readU32(batch, base, available, referenceOffset + 4)
        if (offsetLong > Int.MAX_VALUE || lengthLong > Int.MAX_VALUE) {
            throw ProtocolException("string range is too large", referenceOffset)
        }
        val offset = offsetLong.toInt()
        val length = lengthLong.toInt()
        requireRange(available, offset, length, referenceOffset)
        val view = batch.duplicate()
        view.position(base + offset)
        view.limit(base + offset + length)
        return try {
            StandardCharsets.UTF_8.newDecoder()
                .onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT)
                .decode(view.slice())
                .toString()
        } catch (_: java.nio.charset.CharacterCodingException) {
            throw ProtocolException("string is not valid UTF-8", offset)
        }
    }

    private fun readU16(batch: ByteBuffer, base: Int, available: Int, offset: Int): Int {
        requireRange(available, offset, 2, offset)
        return batch.getShort(base + offset).toInt() and 0xffff
    }

    private fun readU32(batch: ByteBuffer, base: Int, available: Int, offset: Int): Long {
        requireRange(available, offset, 4, offset)
        return batch.getInt(base + offset).toLong() and 0xffff_ffffL
    }

    private fun readU64(batch: ByteBuffer, base: Int, available: Int, offset: Int): Long {
        requireRange(available, offset, 8, offset)
        return batch.getLong(base + offset)
    }

    private fun requireRecordLength(actual: Int, expected: Int, offset: Int) {
        if (actual != expected) {
            throw ProtocolException("invalid record length $actual for tag", offset + 2)
        }
    }

    private fun requireRange(available: Int, offset: Int, length: Int, errorOffset: Int) {
        if (offset < 0 || length < 0 || offset.toLong() + length > available.toLong()) {
            throw ProtocolException("truncated or out-of-range data", errorOffset)
        }
    }
}

/** One rung of the type ladder. Sizes are sp, spacing may be negative. */
data class TypeToken(
    val size: Float,
    val weight: Int,
    val lineHeight: Float,
    val letterSpacing: Float,
    val monospace: Boolean,
)

/**
 * The generated half of one design system's tables: colours, type, shapes and spacing.
 *
 * Arrays are indexed by the role's ordinal, which matches its wire tag minus one.
 * The rules that consume them (elevation rendering, ButtonVariant styling, motion) are
 * written by hand in the Renderer.
 */
class DesignTokenTable(
    val system: DesignSystem,
    /** The published guideline these values come from. */
    val reference: String,
    val defaultFamily: String,
    val monospaceFamily: String,
    private val lightColors: IntArray,
    private val darkColors: IntArray,
    private val typeScale: Array<TypeToken>,
    private val shapeRadii: FloatArray,
    private val spaces: FloatArray,
) {
    /** The 0xAARRGGBB value for a role. `dark` is the scheme the Renderer resolved. */
    fun color(role: ColorRole, dark: Boolean): Int =
        if (dark) darkColors[role.ordinal] else lightColors[role.ordinal]

    fun type(role: TypeRole): TypeToken = typeScale[role.ordinal]

    /** Corner radius in dp. */
    fun radius(role: ShapeRole): Float = shapeRadii[role.ordinal]

    /** Spacing in dp. */
    fun space(role: SpaceRole): Float = spaces[role.ordinal]
}

object DesignTokens {
    val MATERIAL3: DesignTokenTable = DesignTokenTable(
        DesignSystem.Material3,
        "Material 3 baseline scheme and type scale, m3.material.io, 2024 baseline",
        "Roboto",
        "Roboto Mono",
        intArrayOf(
            0xff6750a4.toInt(), // Primary
            0xffffffff.toInt(), // OnPrimary
            0xff625b71.toInt(), // Secondary
            0xffffffff.toInt(), // OnSecondary
            0xfffef7ff.toInt(), // Surface
            0xff1d1b20.toInt(), // OnSurface
            0xffe7e0ec.toInt(), // SurfaceVariant
            0xff49454f.toInt(), // OnSurfaceVariant
            0xfffef7ff.toInt(), // Background
            0xff1d1b20.toInt(), // OnBackground
            0xff79747e.toInt(), // Outline
            0xffcac4d0.toInt(), // OutlineVariant
            0xffb3261e.toInt(), // Error
            0xffffffff.toInt(), // OnError
            0xfff3edf7.toInt(), // SurfaceContainer
            0xff7d5260.toInt(), // Tertiary
            0xffffffff.toInt(), // OnTertiary
            0xffeaddff.toInt(), // PrimaryContainer
            0xff21005d.toInt(), // OnPrimaryContainer
            0xffe8def8.toInt(), // SecondaryContainer
            0xff1d192b.toInt(), // OnSecondaryContainer
            0xffffd8e4.toInt(), // TertiaryContainer
            0xff31111d.toInt(), // OnTertiaryContainer
        ),
        intArrayOf(
            0xffd0bcff.toInt(), // Primary
            0xff381e72.toInt(), // OnPrimary
            0xffccc2dc.toInt(), // Secondary
            0xff332d41.toInt(), // OnSecondary
            0xff141218.toInt(), // Surface
            0xffe6e0e9.toInt(), // OnSurface
            0xff49454f.toInt(), // SurfaceVariant
            0xffcac4d0.toInt(), // OnSurfaceVariant
            0xff141218.toInt(), // Background
            0xffe6e0e9.toInt(), // OnBackground
            0xff938f99.toInt(), // Outline
            0xff49454f.toInt(), // OutlineVariant
            0xfff2b8b5.toInt(), // Error
            0xff601410.toInt(), // OnError
            0xff211f26.toInt(), // SurfaceContainer
            0xffefb8c8.toInt(), // Tertiary
            0xff492532.toInt(), // OnTertiary
            0xff4f378b.toInt(), // PrimaryContainer
            0xffeaddff.toInt(), // OnPrimaryContainer
            0xff4a4458.toInt(), // SecondaryContainer
            0xffe8def8.toInt(), // OnSecondaryContainer
            0xff633b48.toInt(), // TertiaryContainer
            0xffffd8e4.toInt(), // OnTertiaryContainer
        ),
        arrayOf(
            TypeToken(57.0f, 400, 64.0f, 0.0f, false), // Display
            TypeToken(32.0f, 400, 40.0f, 0.0f, false), // Headline
            TypeToken(22.0f, 400, 28.0f, 0.0f, false), // Title
            TypeToken(16.0f, 500, 24.0f, 0.15f, false), // Subtitle
            TypeToken(16.0f, 400, 24.0f, 0.5f, false), // Body
            TypeToken(16.0f, 500, 24.0f, 0.15f, false), // BodyStrong
            TypeToken(14.0f, 500, 20.0f, 0.1f, false), // Label
            TypeToken(12.0f, 400, 16.0f, 0.4f, false), // Caption
            TypeToken(14.0f, 400, 20.0f, 0.0f, true), // Mono
        ),
        floatArrayOf(0.0f, 4.0f, 8.0f, 12.0f, 16.0f, 1000.0f),
        floatArrayOf(0.0f, 4.0f, 8.0f, 16.0f, 24.0f, 32.0f, 48.0f),
    )

    val CUPERTINO: DesignTokenTable = DesignTokenTable(
        DesignSystem.Cupertino,
        "Apple Human Interface Guidelines, system colors and Dynamic Type, 2024",
        "SF Pro",
        "SF Mono",
        intArrayOf(
            0xff007aff.toInt(), // Primary
            0xffffffff.toInt(), // OnPrimary
            0xff5856d6.toInt(), // Secondary
            0xffffffff.toInt(), // OnSecondary
            0xffffffff.toInt(), // Surface
            0xff000000.toInt(), // OnSurface
            0xffe9e9eb.toInt(), // SurfaceVariant
            0xff3c3c43.toInt(), // OnSurfaceVariant
            0xfff2f2f7.toInt(), // Background
            0xff000000.toInt(), // OnBackground
            0xffc6c6c8.toInt(), // Outline
            0xffe5e5ea.toInt(), // OutlineVariant
            0xffff3b30.toInt(), // Error
            0xffffffff.toInt(), // OnError
            0xffffffff.toInt(), // SurfaceContainer
            0xffaf52de.toInt(), // Tertiary
            0xffffffff.toInt(), // OnTertiary
            0xffd6e4ff.toInt(), // PrimaryContainer
            0xff003070.toInt(), // OnPrimaryContainer
            0xffe2e0ff.toInt(), // SecondaryContainer
            0xff2a1b70.toInt(), // OnSecondaryContainer
            0xfff3ddfb.toInt(), // TertiaryContainer
            0xff3d0b52.toInt(), // OnTertiaryContainer
        ),
        intArrayOf(
            0xff0a84ff.toInt(), // Primary
            0xffffffff.toInt(), // OnPrimary
            0xff5e5ce6.toInt(), // Secondary
            0xffffffff.toInt(), // OnSecondary
            0xff1c1c1e.toInt(), // Surface
            0xffffffff.toInt(), // OnSurface
            0xff2c2c2e.toInt(), // SurfaceVariant
            0xffebebf5.toInt(), // OnSurfaceVariant
            0xff000000.toInt(), // Background
            0xffffffff.toInt(), // OnBackground
            0xff38383a.toInt(), // Outline
            0xff48484a.toInt(), // OutlineVariant
            0xffff453a.toInt(), // Error
            0xffffffff.toInt(), // OnError
            0xff1c1c1e.toInt(), // SurfaceContainer
            0xffbf5af2.toInt(), // Tertiary
            0xffffffff.toInt(), // OnTertiary
            0xff0a2d52.toInt(), // PrimaryContainer
            0xffcfe3ff.toInt(), // OnPrimaryContainer
            0xff262663.toInt(), // SecondaryContainer
            0xffdedcff.toInt(), // OnSecondaryContainer
            0xff3f1a52.toInt(), // TertiaryContainer
            0xfff1d9fa.toInt(), // OnTertiaryContainer
        ),
        arrayOf(
            TypeToken(34.0f, 400, 41.0f, 0.37f, false), // Display
            TypeToken(28.0f, 400, 34.0f, 0.36f, false), // Headline
            TypeToken(22.0f, 400, 28.0f, 0.35f, false), // Title
            TypeToken(17.0f, 600, 22.0f, -0.41f, false), // Subtitle
            TypeToken(17.0f, 400, 22.0f, -0.41f, false), // Body
            TypeToken(17.0f, 600, 22.0f, -0.41f, false), // BodyStrong
            TypeToken(15.0f, 400, 20.0f, -0.24f, false), // Label
            TypeToken(12.0f, 400, 16.0f, 0.0f, false), // Caption
            TypeToken(15.0f, 400, 20.0f, 0.0f, true), // Mono
        ),
        floatArrayOf(0.0f, 4.0f, 8.0f, 10.0f, 14.0f, 1000.0f),
        floatArrayOf(0.0f, 4.0f, 8.0f, 16.0f, 20.0f, 32.0f, 44.0f),
    )

    val FLUENT: DesignTokenTable = DesignTokenTable(
        DesignSystem.Fluent,
        "WinUI / Fluent 2 web and Windows tokens, fluent2.microsoft.design, 2024",
        "Segoe UI Variable",
        "Cascadia Mono",
        intArrayOf(
            0xff0f6cbd.toInt(), // Primary
            0xffffffff.toInt(), // OnPrimary
            0xffebf3fc.toInt(), // Secondary
            0xff0f548c.toInt(), // OnSecondary
            0xffffffff.toInt(), // Surface
            0xff242424.toInt(), // OnSurface
            0xffeaeaea.toInt(), // SurfaceVariant
            0xff424242.toInt(), // OnSurfaceVariant
            0xfff3f3f3.toInt(), // Background
            0xff242424.toInt(), // OnBackground
            0xffd1d1d1.toInt(), // Outline
            0xffe0e0e0.toInt(), // OutlineVariant
            0xffc50f1f.toInt(), // Error
            0xffffffff.toInt(), // OnError
            0xffffffff.toInt(), // SurfaceContainer
            0xff8764b8.toInt(), // Tertiary
            0xffffffff.toInt(), // OnTertiary
            0xffcfe4fa.toInt(), // PrimaryContainer
            0xff0c3b5e.toInt(), // OnPrimaryContainer
            0xffb4d6fa.toInt(), // SecondaryContainer
            0xff0b3350.toInt(), // OnSecondaryContainer
            0xffe8dcf7.toInt(), // TertiaryContainer
            0xff341a5e.toInt(), // OnTertiaryContainer
        ),
        intArrayOf(
            0xff479ef5.toInt(), // Primary
            0xff000000.toInt(), // OnPrimary
            0xff0c3b5e.toInt(), // Secondary
            0xffffffff.toInt(), // OnSecondary
            0xff292929.toInt(), // Surface
            0xffffffff.toInt(), // OnSurface
            0xff333333.toInt(), // SurfaceVariant
            0xffd6d6d6.toInt(), // OnSurfaceVariant
            0xff1f1f1f.toInt(), // Background
            0xffffffff.toInt(), // OnBackground
            0xff666666.toInt(), // Outline
            0xff3d3d3d.toInt(), // OutlineVariant
            0xffdc626d.toInt(), // Error
            0xff000000.toInt(), // OnError
            0xff2b2b2b.toInt(), // SurfaceContainer
            0xffb18cd9.toInt(), // Tertiary
            0xff22103a.toInt(), // OnTertiary
            0xff0c3b5e.toInt(), // PrimaryContainer
            0xffcfe4fa.toInt(), // OnPrimaryContainer
            0xff123d61.toInt(), // SecondaryContainer
            0xffb4d6fa.toInt(), // OnSecondaryContainer
            0xff3b2159.toInt(), // TertiaryContainer
            0xffe8dcf7.toInt(), // OnTertiaryContainer
        ),
        arrayOf(
            TypeToken(40.0f, 600, 52.0f, 0.0f, false), // Display
            TypeToken(28.0f, 600, 36.0f, 0.0f, false), // Headline
            TypeToken(20.0f, 600, 28.0f, 0.0f, false), // Title
            TypeToken(16.0f, 600, 22.0f, 0.0f, false), // Subtitle
            TypeToken(14.0f, 400, 20.0f, 0.0f, false), // Body
            TypeToken(14.0f, 600, 20.0f, 0.0f, false), // BodyStrong
            TypeToken(12.0f, 400, 16.0f, 0.0f, false), // Label
            TypeToken(12.0f, 400, 16.0f, 0.0f, false), // Caption
            TypeToken(13.0f, 400, 18.0f, 0.0f, true), // Mono
        ),
        floatArrayOf(0.0f, 2.0f, 3.0f, 4.0f, 8.0f, 1000.0f),
        floatArrayOf(0.0f, 2.0f, 4.0f, 8.0f, 12.0f, 20.0f, 32.0f),
    )

    val GNOME: DesignTokenTable = DesignTokenTable(
        DesignSystem.Gnome,
        "GNOME Human Interface Guidelines and the libadwaita named colours, GNOME 50",
        "Cantarell",
        "Source Code Pro",
        intArrayOf(
            0xff3584e4.toInt(), // Primary
            0xffffffff.toInt(), // OnPrimary
            0xff9141ac.toInt(), // Secondary
            0xffffffff.toInt(), // OnSecondary
            0xffffffff.toInt(), // Surface
            0xff2e3436.toInt(), // OnSurface
            0xffebebeb.toInt(), // SurfaceVariant
            0xff5e5c64.toInt(), // OnSurfaceVariant
            0xfffafafa.toInt(), // Background
            0xff2e3436.toInt(), // OnBackground
            0xffcdc7c2.toInt(), // Outline
            0xffe6e3e1.toInt(), // OutlineVariant
            0xffe01b24.toInt(), // Error
            0xffffffff.toInt(), // OnError
            0xffebebeb.toInt(), // SurfaceContainer
            0xff2190a4.toInt(), // Tertiary
            0xffffffff.toInt(), // OnTertiary
            0xffd4e5fb.toInt(), // PrimaryContainer
            0xff0d3b70.toInt(), // OnPrimaryContainer
            0xffecd9f1.toInt(), // SecondaryContainer
            0xff45164f.toInt(), // OnSecondaryContainer
            0xffcfe9ed.toInt(), // TertiaryContainer
            0xff0a3d45.toInt(), // OnTertiaryContainer
        ),
        intArrayOf(
            0xff3584e4.toInt(), // Primary
            0xffffffff.toInt(), // OnPrimary
            0xffc061cb.toInt(), // Secondary
            0xffffffff.toInt(), // OnSecondary
            0xff1e1e1e.toInt(), // Surface
            0xffffffff.toInt(), // OnSurface
            0xff303030.toInt(), // SurfaceVariant
            0xffc0bfbc.toInt(), // OnSurfaceVariant
            0xff242424.toInt(), // Background
            0xffffffff.toInt(), // OnBackground
            0xff52514f.toInt(), // Outline
            0xff3a3a3a.toInt(), // OutlineVariant
            0xffff7b63.toInt(), // Error
            0xff2a0a06.toInt(), // OnError
            0xff303030.toInt(), // SurfaceContainer
            0xff2190a4.toInt(), // Tertiary
            0xffffffff.toInt(), // OnTertiary
            0xff1b3c5e.toInt(), // PrimaryContainer
            0xffcfe0f7.toInt(), // OnPrimaryContainer
            0xff44234c.toInt(), // SecondaryContainer
            0xffecd9f1.toInt(), // OnSecondaryContainer
            0xff134249.toInt(), // TertiaryContainer
            0xffcfe9ed.toInt(), // OnTertiaryContainer
        ),
        arrayOf(
            TypeToken(44.0f, 800, 52.0f, -0.5f, false), // Display
            TypeToken(32.0f, 800, 40.0f, -0.25f, false), // Headline
            TypeToken(24.0f, 700, 32.0f, 0.0f, false), // Title
            TypeToken(20.0f, 700, 28.0f, 0.0f, false), // Subtitle
            TypeToken(15.0f, 400, 22.0f, 0.0f, false), // Body
            TypeToken(15.0f, 700, 22.0f, 0.0f, false), // BodyStrong
            TypeToken(13.0f, 700, 18.0f, 0.1f, false), // Label
            TypeToken(12.0f, 400, 16.0f, 0.0f, false), // Caption
            TypeToken(14.0f, 400, 20.0f, 0.0f, true), // Mono
        ),
        floatArrayOf(0.0f, 4.0f, 6.0f, 8.0f, 12.0f, 1000.0f),
        floatArrayOf(0.0f, 3.0f, 6.0f, 12.0f, 18.0f, 24.0f, 36.0f),
    )

    val BREEZE: DesignTokenTable = DesignTokenTable(
        DesignSystem.Breeze,
        "KDE Breeze colour schemes and the KDE Human Interface Guidelines, Plasma 6",
        "Noto Sans",
        "Hack",
        intArrayOf(
            0xff3daee9.toInt(), // Primary
            0xff06222e.toInt(), // OnPrimary
            0xff16a085.toInt(), // Secondary
            0xff03201b.toInt(), // OnSecondary
            0xfffcfcfc.toInt(), // Surface
            0xff232629.toInt(), // OnSurface
            0xffe1e3e5.toInt(), // SurfaceVariant
            0xff4d5052.toInt(), // OnSurfaceVariant
            0xffeff0f1.toInt(), // Background
            0xff232629.toInt(), // OnBackground
            0xffbdc3c7.toInt(), // Outline
            0xffd8dbdd.toInt(), // OutlineVariant
            0xffda4453.toInt(), // Error
            0xffffffff.toInt(), // OnError
            0xfffcfcfc.toInt(), // SurfaceContainer
            0xfff67400.toInt(), // Tertiary
            0xff2b1200.toInt(), // OnTertiary
            0xffd3ecf9.toInt(), // PrimaryContainer
            0xff0b3b52.toInt(), // OnPrimaryContainer
            0xffd2ece5.toInt(), // SecondaryContainer
            0xff083b31.toInt(), // OnSecondaryContainer
            0xfffae0c4.toInt(), // TertiaryContainer
            0xff4a2c00.toInt(), // OnTertiaryContainer
        ),
        intArrayOf(
            0xff3daee9.toInt(), // Primary
            0xff06222e.toInt(), // OnPrimary
            0xff1abc9c.toInt(), // Secondary
            0xff03201b.toInt(), // OnSecondary
            0xff1b1e20.toInt(), // Surface
            0xfffcfcfc.toInt(), // OnSurface
            0xff31363b.toInt(), // SurfaceVariant
            0xffbdc3c7.toInt(), // OnSurfaceVariant
            0xff232629.toInt(), // Background
            0xfffcfcfc.toInt(), // OnBackground
            0xff4d5155.toInt(), // Outline
            0xff3f4449.toInt(), // OutlineVariant
            0xffed8079.toInt(), // Error
            0xff2a0806.toInt(), // OnError
            0xff1b1e20.toInt(), // SurfaceContainer
            0xfff8a44c.toInt(), // Tertiary
            0xff2b1200.toInt(), // OnTertiary
            0xff123b4f.toInt(), // PrimaryContainer
            0xffcde6f5.toInt(), // OnPrimaryContainer
            0xff103a32.toInt(), // SecondaryContainer
            0xffcfe8e0.toInt(), // OnSecondaryContainer
            0xff4a3113.toInt(), // TertiaryContainer
            0xfff8dfc3.toInt(), // OnTertiaryContainer
        ),
        arrayOf(
            TypeToken(34.0f, 600, 40.0f, 0.0f, false), // Display
            TypeToken(26.0f, 600, 32.0f, 0.0f, false), // Headline
            TypeToken(19.0f, 600, 24.0f, 0.0f, false), // Title
            TypeToken(16.0f, 500, 21.0f, 0.0f, false), // Subtitle
            TypeToken(13.0f, 400, 19.0f, 0.0f, false), // Body
            TypeToken(13.0f, 600, 19.0f, 0.0f, false), // BodyStrong
            TypeToken(12.0f, 500, 16.0f, 0.2f, false), // Label
            TypeToken(11.0f, 400, 15.0f, 0.0f, false), // Caption
            TypeToken(12.0f, 400, 17.0f, 0.0f, true), // Mono
        ),
        floatArrayOf(0.0f, 2.0f, 3.0f, 4.0f, 6.0f, 1000.0f),
        floatArrayOf(0.0f, 2.0f, 4.0f, 8.0f, 12.0f, 18.0f, 24.0f),
    )

    val DEEPIN: DesignTokenTable = DesignTokenTable(
        DesignSystem.Deepin,
        "Deepin Design specification and the DTK control defaults, deepin 23",
        "Noto Sans",
        "Noto Sans Mono",
        intArrayOf(
            0xff0081ff.toInt(), // Primary
            0xffffffff.toInt(), // OnPrimary
            0xfff2a13c.toInt(), // Secondary
            0xff2b1a05.toInt(), // OnSecondary
            0xfffffdfa.toInt(), // Surface
            0xff2c2622.toInt(), // OnSurface
            0xfff0e9e0.toInt(), // SurfaceVariant
            0xff6b5f56.toInt(), // OnSurfaceVariant
            0xfffaf7f2.toInt(), // Background
            0xff2c2622.toInt(), // OnBackground
            0xffd9cdc0.toInt(), // Outline
            0xffece3d9.toInt(), // OutlineVariant
            0xffe35c4b.toInt(), // Error
            0xffffffff.toInt(), // OnError
            0xffffffff.toInt(), // SurfaceContainer
            0xff7a5bd6.toInt(), // Tertiary
            0xffffffff.toInt(), // OnTertiary
            0xffd3e7ff.toInt(), // PrimaryContainer
            0xff00366e.toInt(), // OnPrimaryContainer
            0xfffae4c6.toInt(), // SecondaryContainer
            0xff4a3001.toInt(), // OnSecondaryContainer
            0xffe4dcfa.toInt(), // TertiaryContainer
            0xff2c1f63.toInt(), // OnTertiaryContainer
        ),
        intArrayOf(
            0xff3ba2ff.toInt(), // Primary
            0xff04203a.toInt(), // OnPrimary
            0xffffb964.toInt(), // Secondary
            0xff33200a.toInt(), // OnSecondary
            0xff2b2726.toInt(), // Surface
            0xfff5efe9.toInt(), // OnSurface
            0xff3a3533.toInt(), // SurfaceVariant
            0xffc4b8ad.toInt(), // OnSurfaceVariant
            0xff232020.toInt(), // Background
            0xfff5efe9.toInt(), // OnBackground
            0xff574f4b.toInt(), // Outline
            0xff383230.toInt(), // OutlineVariant
            0xffff8a73.toInt(), // Error
            0xff34110a.toInt(), // OnError
            0xff302b29.toInt(), // SurfaceContainer
            0xff9f8ae3.toInt(), // Tertiary
            0xff1d0f45.toInt(), // OnTertiary
            0xff0d3355.toInt(), // PrimaryContainer
            0xffcfe3fb.toInt(), // OnPrimaryContainer
            0xff4a3517.toInt(), // SecondaryContainer
            0xfff8e2c5.toInt(), // OnSecondaryContainer
            0xff362b5e.toInt(), // TertiaryContainer
            0xffe1d9f7.toInt(), // OnTertiaryContainer
        ),
        arrayOf(
            TypeToken(40.0f, 600, 50.0f, 0.0f, false), // Display
            TypeToken(30.0f, 600, 38.0f, 0.0f, false), // Headline
            TypeToken(22.0f, 500, 30.0f, 0.0f, false), // Title
            TypeToken(18.0f, 500, 26.0f, 0.0f, false), // Subtitle
            TypeToken(14.0f, 400, 21.0f, 0.0f, false), // Body
            TypeToken(14.0f, 600, 21.0f, 0.0f, false), // BodyStrong
            TypeToken(13.0f, 500, 18.0f, 0.3f, false), // Label
            TypeToken(12.0f, 400, 17.0f, 0.0f, false), // Caption
            TypeToken(13.0f, 400, 19.0f, 0.0f, true), // Mono
        ),
        floatArrayOf(0.0f, 6.0f, 8.0f, 12.0f, 18.0f, 1000.0f),
        floatArrayOf(0.0f, 4.0f, 10.0f, 16.0f, 20.0f, 30.0f, 40.0f),
    )

    fun of(system: DesignSystem): DesignTokenTable = when (system) {
        DesignSystem.Material3 -> MATERIAL3
        DesignSystem.Cupertino -> CUPERTINO
        DesignSystem.Fluent -> FLUENT
        DesignSystem.Gnome -> GNOME
        DesignSystem.Breeze -> BREEZE
        DesignSystem.Deepin -> DEEPIN
    }
}
