#!/usr/bin/env bash
# Runs the web boundary tests against a real Host.
# Usage: ./test-boundary.sh [--debug]
#
# `./kotlin test -p wasmJs` on its own reports that the Host is missing and passes, because
# the renderer is worked on without the other side being built. This builds the Host first,
# which is what makes those tests exercise the boundary rather than skip it.
#
# The Host has to be beside the test page, and the page a Kotlin/Wasm test runs on is
# generated by the toolchain: `testResources` is the one tree it copies, so that is where
# `build-host.sh` puts a second copy.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
module_dir="$(cd "$script_dir/.." && pwd)"
renderer_root="$(cd "$module_dir/.." && pwd)"

"$script_dir/build-host.sh" "$@"

cd "$renderer_root"
exec ./kotlin test -p wasmJs --include-module web --include-classes \
    dioxus.compose.ui.platform.WebBoundaryTest
