// Generated by `cargo run -p dioxus-compose --bin codegen`. DO NOT EDIT.
package dalvik.annotation.optimization

/**
 * The runtime's marker for a native method that needs no thread state transition.
 *
 * The runtime carries it, but `android.jar` does not declare it, so the only way to apply
 * it from application code is to declare it. It is matched by type descriptor, and a
 * runtime that does not know it ignores it, which is why an unannotated call still works.
 *
 * A method carrying it must not run long: the thread stays in the runnable state, so the
 * garbage collector cannot suspend it while the call is in flight. Only calls that cannot
 * run the VirtualDom carry it.
 */
@Retention(AnnotationRetention.BINARY)
@Target(AnnotationTarget.FUNCTION)
annotation class FastNative
