// Generated by `cargo run -p dioxus-compose --bin codegen`. DO NOT EDIT.
@file:JvmName("HostBridge")

package dioxus.compose.ui.platform

import android.util.Log
import dalvik.annotation.optimization.FastNative
import java.nio.ByteBuffer

// The Android boundary.
//
// Every declaration below is generated from the Rust boundary schema, so it cannot drift
// from the shims that implement it. A batch-returning call writes the slots below into the
// caller's reusable LongArray and copies nothing: the batch itself stays in the Host's
// arena, which the caller reads through one direct ByteBuffer.

/** Slot 0: the batch's start inside the arena. */
const val OUT_BATCH_OFFSET: Int = 0
/** Slot 1: the batch's length in bytes. */
const val OUT_BATCH_LENGTH: Int = 1
/** Slot 2: the handler's synchronous result. */
const val OUT_RESULT: Int = 2
/** Slot 3: the arena's base address, which moves when it grows. */
const val OUT_ARENA_ADDRESS: Int = 3
/** Slot 4: the arena's capacity in bytes. */
const val OUT_ARENA_CAPACITY: Int = 4

/** The size of the `out` array a batch-returning call expects. */
const val OUT_SLOTS: Int = 5

/** `Init`, which calls `dioxus_compose_host_init`. */
external fun nativeInit(handshake: ByteBuffer, handshakeLength: Int, out: LongArray): Int

/** `DispatchEvent`, which calls `dioxus_compose_host_dispatch_event`. */
external fun nativeDispatchEvent(event: ByteBuffer, eventLength: Int, out: LongArray): Int

/** `RenderFrame`, which calls `dioxus_compose_host_render_frame`. */
external fun nativeRenderFrame(frameTimeNanos: Long, out: LongArray): Int

/** `ReleaseBatch`, which calls `dioxus_compose_host_release_batch`. */
@FastNative
external fun nativeReleaseBatch(): Int

/** `Shutdown`, which calls `dioxus_compose_host_shutdown`. */
external fun nativeShutdown(): Int

/**
 * A view of the Host's batch arena.
 *
 * Null before the Host exists. Ask again whenever `OUT_ARENA_ADDRESS` changes: a grown
 * arena is a new allocation, and the old view points at freed memory.
 */
external fun nativeArenaBuffer(): ByteBuffer?

/**
 * Called from a Host worker thread through JNI.
 *
 * It must stay cheap and thread-safe: it only bumps a counter the UI thread observes
 * inside its frame clock, so any number of requests between two frames become one frame.
 */
fun onFrameRequested() {
    // Evidence that domain work stays off the UI thread, off by default. Turn it on with
    // `adb shell setprop log.tag.dxc-frame VERBOSE`: the thread named in the line is the
    // Host worker that asked, and it is never the UI thread.
    if (Log.isLoggable(FRAME_TAG, Log.VERBOSE)) {
        Log.v(FRAME_TAG, "frame requested by ${Thread.currentThread().name}")
    }
    FrameRequests.request()
}

private const val FRAME_TAG = "dxc-frame"
