// Generated by `cargo run -p dioxus-compose --bin codegen`. DO NOT EDIT.
@file:OptIn(
    kotlin.js.ExperimentalWasmJsInterop::class,
    kotlin.wasm.ExperimentalWasmInterop::class,
)

package dioxus.compose.ui.platform

import kotlin.wasm.WasmExport

// The web boundary.
//
// One WebAssembly.Memory holds both modules. The Kotlin module defines and exports it,
// because a Kotlin/Wasm module cannot import one, and the Host's module is linked against
// it, so a batch is read where the Host wrote it and no byte of it is copied.
//
// Every call below goes through a JavaScript arrow function of a fixed shape, measured at
// about 12ns. It is there because the two halves of the wiring cannot both be had: a wasm
// import bound straight to a wasm export costs 1.5ns but has to be supplied before the
// Kotlin module is instantiated, and the memory it would need to share does not exist
// until that instantiation. The forwarder passes its arguments on and does nothing else:
// no encoding, no copy, no queue.
//
// The other direction has no JavaScript on it. The page hands the Host's instantiation the
// function object Kotlin exports below, and the engine binds that edge as a wasm call.

/**
 * The first address that belongs to the Host's module.
 *
 * Below it is this module's `kotlin.wasm.unsafe` allocator; at and above it are the
 * Host's data, stack and heap. Two allocators hand out addresses in one memory, and an
 * overlap does not crash, it draws the wrong screen, so every address that crosses is
 * checked against this line.
 */
const val RUST_REGION_BASE: Int = 4194304

/**
 * The batch record the Host writes, field by field.
 *
 * A wasm32 `#[repr(C)]` layout: two four byte fields and then an eight byte one, which
 * the padding before it puts at 8. The Host's generated shims assert this against the
 * layout its compiler chose, so a disagreement stops that build.
 */
/** where the batch starts, as an address in the shared memory. */
const val BATCH_ADDRESS_OFFSET: Int = 0
/** the batch's length in bytes. */
const val BATCH_LENGTH_OFFSET: Int = 4
/** the handler's synchronous result. */
const val BATCH_RESULT_OFFSET: Int = 8

/** How long that record is, padding included. */
const val BATCH_BYTES: Int = 16

/**
 * Where the event buffer starts inside the block the Host lends this side.
 *
 * The out record comes first and the event buffer follows it. Both belong to the Host,
 * because `kotlin.wasm.unsafe` only hands out addresses inside a scope and this side
 * needs two buffers that outlive every scope it could open.
 */
const val EVENT_BUFFER_OFFSET: Int = 16

/** How much room there is to encode one event into. */
const val EVENT_BUFFER_BYTES: Int = 4096

/** `Init`, which calls `dioxus_compose_host_init`. */
@JsFun("(handshake, handshakeLength, out) => globalThis.__dioxusComposeHost.dioxus_compose_host_web_init(handshake, handshakeLength, out)")
external fun hostInit(handshake: Int, handshakeLength: Int, out: Int): Int

/** `DispatchEvent`, which calls `dioxus_compose_host_dispatch_event`. */
@JsFun("(event, eventLength, out) => globalThis.__dioxusComposeHost.dioxus_compose_host_web_dispatch_event(event, eventLength, out)")
external fun hostDispatchEvent(event: Int, eventLength: Int, out: Int): Int

/** `RenderFrame`, which calls `dioxus_compose_host_render_frame`. */
@JsFun("(frameTimeNanosLow, frameTimeNanosHigh, out) => globalThis.__dioxusComposeHost.dioxus_compose_host_web_render_frame(frameTimeNanosLow, frameTimeNanosHigh, out)")
external fun hostRenderFrame(frameTimeNanosLow: Int, frameTimeNanosHigh: Int, out: Int): Int

/** `ReleaseBatch`, which calls `dioxus_compose_host_release_batch`. */
@JsFun("(out) => globalThis.__dioxusComposeHost.dioxus_compose_host_web_release_batch(out)")
external fun hostReleaseBatch(out: Int): Int

/** `Shutdown`, which calls `dioxus_compose_host_shutdown`. */
@JsFun("() => globalThis.__dioxusComposeHost.dioxus_compose_host_web_shutdown()")
external fun hostShutdown(): Int

/**
 * Instantiates the Host on this module's memory and answers with the address of the block
 * it lends back: the record a call reports into, and the buffer an event is encoded in.
 * Zero means there is no Host on this page.
 *
 * Called once, from `main`. That is the first moment at which both halves exist: this
 * module's own instantiation created the memory the Host imports, and the page compiled the
 * Host's module before that started.
 */
@JsFun(
    """() => {
  const compiled = globalThis.__dioxusComposeHostModule;
  if (!compiled) return 0;
  const memory = wasmExports.memory;
  const pages = memory.buffer.byteLength / 65536;
  // This module's memory starts at zero pages and the Host's import declares a minimum,
  // so the two module types do not match until this has run.
  if (pages < 128) memory.grow(128 - pages);
  // The wasm-bindgen placeholders dioxus-core brings in through subsecond. A browser will
  // not instantiate a module with an import nobody supplied, used or not, and their names
  // carry a per-version hash, so this answers whatever is asked rather than a list that
  // would go stale. Nothing on the boundary goes near one.
  const unbound = (namespace) => new Proxy({}, {
    get: (_, name) => () => {
      throw new Error('dioxus-compose: the Host called ' + namespace + '.' + String(name) +
        ', which is a wasm-bindgen import this page does not provide. Nothing on the ' +
        'boundary uses one, so a call here means the Host reached JavaScript through a ' +
        'dependency rather than through the boundary.');
    },
  });
  const host = new WebAssembly.Instance(compiled, {
    env: { memory },
    dioxus_compose_renderer: {
      // The exported function object itself, not a closure around it: bound this way the
      // engine builds no JavaScript frame for the call.
      dioxus_compose_renderer_request_frame:
        wasmExports.dioxus_compose_renderer_request_frame,
    },
    __wbindgen_placeholder__: unbound('__wbindgen_placeholder__'),
    __wbindgen_externref_xform__: unbound('__wbindgen_externref_xform__'),
  }).exports;
  globalThis.__dioxusComposeHost = host;
  const block = host.dioxus_compose_host_web_start();
  if (block < 4194304) {
    // Either the Host could not start, or its data landed in the half of the memory this
    // module's allocator uses. The second draws a wrong screen instead of failing, so
    // neither is allowed to become the first boundary call.
    globalThis.__dioxusComposeHost = undefined;
    throw new Error('dioxus-compose: the Host reported its boundary block at ' + block +
      ', which is not inside the region above 4194304 that it was linked into. ' +
      'Check that it was linked with --import-memory and --global-base.');
  }
  return block;
}""",
)
external fun installHost(): Int

/**
 * Called by the Host when work done off the frame loop needs one.
 *
 * A browser tab is one thread, so this arrives on the same thread that will answer it.
 * It only bumps a counter the frame clock observes, so any number of requests between
 * two frames become one frame. The page also calls it once after the Host is installed,
 * which is what gets the first tree drawn.
 */
@WasmExport("dioxus_compose_renderer_request_frame")
fun onFrameRequested() {
    FrameRequests.request()
}
