[workspace]
members = [
    "dioxus-compose",
    "samples/calculator",
    "samples/chat",
    "samples/notepad",
    "samples/todo",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
dioxus-core = "0.7.10"
dioxus-core-macro = "0.7.10"
dioxus-hooks = "0.7"
dioxus-signals = "0.7"
