// Generated by `cargo run -p dioxus-compose --bin codegen`. DO NOT EDIT.
//
// The page's half of the web boundary.
//
// `WebAssembly.instantiate` wants every import before it will give you an instance, and
// the two modules each hold what the other needs: the Renderer's module defines the one
// linear memory, which the Host imports, and the Host exports the functions the Renderer
// calls. Nothing breaks that cycle inside wasm, so the page breaks it in three steps.
//
//   1. This module is evaluated before the Renderer's, and compiles the Host. Compiling
//      needs no imports.
//   2. The Renderer's module is instantiated, which is what creates the memory.
//   3. The Renderer's `main` calls `instantiate` below, which is synchronous, because the
//      module was already compiled in step 1.
//
// By step 3 the Renderer's exports exist, so the Host's frame request is bound to the
// exported function object itself and the engine treats that edge as a wasm call. The
// other direction, Renderer to Host, is the generated arrow functions in the Kotlin
// bridge, and they pass their arguments on and do nothing else.

const HOST_WASM = './dioxus_compose_host.wasm';
/** What the Host's module declares as the minimum size of the memory it imports. */
const MEMORY_MIN_PAGES = 128;
const WASM_PAGE_BYTES = 65536;
/** The first address that belongs to the Host. Its own block has to be above it. */
const RUST_REGION_BASE = 4194304;

/**
 * The import namespaces wasm-bindgen leaves behind, and what they resolve to.
 *
 * `dioxus-core` depends on `subsecond`, which depends on `js-sys` and `web-sys`, so the
 * Host's module carries wasm-bindgen's placeholder imports whether or not any of it is
 * reachable. A browser will not instantiate a module with an import nobody supplied, used
 * or not, so they have to be answered. Nothing on the boundary goes near them, and their
 * names carry a per-version hash, so the answer is a namespace that reports whatever is
 * asked of it rather than a list that would go stale.
 *
 * Running the `wasm-bindgen` tool over the module would rewrite these into real glue, at
 * the cost of that tool owning the instantiation this file owns.
 */
const unbound = (namespace) =>
  new Proxy(
    {},
    {
      get: (_, name) => () => {
        throw new Error(
          `dioxus-compose: the Host called ${namespace}.${String(name)}, which is a ` +
            'wasm-bindgen import this page does not provide. Nothing on the boundary ' +
            'uses one, so a call here means the Host reached JavaScript through a ' +
            'dependency rather than through the boundary.',
        );
      },
    },
  );

let compiled = null;
try {
  compiled = await WebAssembly.compileStreaming(
    fetch(new URL(HOST_WASM, import.meta.url)),
  );
} catch (error) {
  // No Host on this page, which is a page serving the renderer on its own. The renderer
  // falls back to its scripted development host, and this says why on the console rather
  // than leaving an empty screen to be puzzled over.
  console.info(
    `dioxus-compose: no Host module beside this page (${HOST_WASM}: ${error}). ` +
      'The renderer will draw its development host instead.',
  );
}

globalThis.__dioxusComposeHostLoader = {
  /**
   * Instantiates the Host on the Renderer's memory.
   *
   * Returns the address of the block the Host lends back: the batch record the Renderer
   * reads a reply out of, and the buffer it encodes an event into. Zero when there is no
   * Host, which is the answer the Renderer treats as "run the development host".
   */
  instantiate(exports) {
    if (compiled === null) return 0;
    const memory = exports.memory;
    const pages = memory.buffer.byteLength / WASM_PAGE_BYTES;
    // The Renderer's memory starts at zero pages and the Host's import declares a
    // minimum, so the two types do not match until this has run.
    if (pages < MEMORY_MIN_PAGES) memory.grow(MEMORY_MIN_PAGES - pages);
    const host = new WebAssembly.Instance(compiled, {
      env: { memory },
      __wbindgen_placeholder__: unbound('__wbindgen_placeholder__'),
      __wbindgen_externref_xform__: unbound('__wbindgen_externref_xform__'),
      dioxus_compose_renderer: {
        // The exported function object itself, not a closure around it: bound this
        // way the engine builds no JavaScript frame for the call.
        dioxus_compose_renderer_request_frame:
          exports.dioxus_compose_renderer_request_frame,
      },
    }).exports;
    globalThis.__dioxusComposeHost = host;
    const block = host.dioxus_compose_host_web_start();
    if (block < RUST_REGION_BASE) {
      // Either the Host could not start, or its data landed in the half of the memory the
      // Renderer's allocator uses. The second one would draw a wrong screen instead of
      // failing, so neither is allowed to become the first boundary call.
      globalThis.__dioxusComposeHost = undefined;
      throw new Error(
        `dioxus-compose: the Host reported its boundary block at ${block}, which is not ` +
          `inside the region above ${RUST_REGION_BASE} that it was linked into. ` +
          'Check that the Host was linked with --global-base and --import-memory.',
      );
    }
    return block;
  },
};
