// Generated by `cargo run -p dioxus-compose --bin codegen`. DO NOT EDIT.
//
// The page's half of the web boundary: compile the Host, and leave it where the Renderer
// will look for it.
//
// `WebAssembly.instantiate` wants every import before it will give you an instance, and
// the two modules each hold what the other needs. The Renderer's module defines the one
// linear memory, which the Host imports; the Host exports the functions the Renderer
// calls. Nothing inside wasm breaks that cycle, so the page breaks it by order:
//
//   1. This module is evaluated before the Renderer's, because it comes first on the page,
//      and compiles the Host. Compiling needs no imports.
//   2. The Renderer's module is instantiated, which is what creates the memory.
//   3. The Renderer's `main` instantiates the Host on that memory, and does it
//      synchronously, because the module was already compiled in step 1.
//
// Only step 1 is here. Step 3 needs the memory and the Renderer's own exports, and only
// the Renderer's module can name either, so it sits in the generated Kotlin beside the
// forwarders.

const HOST_WASM = './dioxus_compose_host.wasm';

globalThis.__dioxusComposeHostModule = null;
try {
  globalThis.__dioxusComposeHostModule = await WebAssembly.compileStreaming(
    fetch(new URL(HOST_WASM, import.meta.url)),
  );
} catch (error) {
  // No Host on this page, which is a page serving the renderer on its own. The renderer
  // falls back to its scripted development host, and this says why on the console rather
  // than leaving an empty screen to be puzzled over.
  console.info(
    `dioxus-compose: no Host module beside this page (${HOST_WASM}: ${error}). ` +
      'The renderer will draw its development host instead.',
  );
}
