@file:OptIn(kotlin.js.ExperimentalWasmJsInterop::class)

package dioxus.compose.ui.platform

import dioxus.compose.protocol.HostEvent
import dioxus.compose.protocol.Mutation
import dioxus.compose.protocol.PropertyKind
import dioxus.compose.protocol.WidgetKind
import dioxus.compose.ui.node.Node
import dioxus.compose.ui.node.NodeTable
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The web boundary, running in a browser, against the Host built from the same Rust source
 * the desktop renderer runs.
 *
 * What is under test is the real thing all the way down: the generated forwarders, the
 * generated wasm shims, the generated instantiation and one `WebAssembly.Memory` that both
 * modules read in place. The only part written here is fetching the module, because the page
 * a Kotlin/Wasm test runs on is generated by the toolchain and cannot load a module of its
 * own to do it.
 *
 * Run it with the Host beside the page:
 * ```sh
 * dioxus-compose-renderer/web/scripts/build-host.sh
 * cd dioxus-compose-renderer && ./kotlin test -p wasmJs
 * ```
 * Without that module the tests report what is missing and pass, because the renderer is
 * worked on without the other side being built.
 */
class WebBoundaryTest {
    @Test
    fun pr6_the_two_modules_share_one_memory_and_the_batch_is_read_in_place() {
        val connection = hostOrNull() ?: return
        val table = NodeTable()
        val mutations = mutableListOf<Mutation>()
        connection.init { mutation ->
            mutations += mutation
            table.apply(mutation)
        }
        assertTrue(
            mutations.any { it is Mutation.Create },
            "the initial batch has to create the tree, got ${mutations.size} records",
        )
        assertTrue(table.roots.isNotEmpty(), "the tree has no roots")
        assertTrue(
            table.drainErrors().isEmpty(),
            "the batch decoded with errors, so the two sides disagree about the arena",
        )
        connection.shutdown()
    }

    /**
     * The click reaches Rust and the state it changed comes back.
     *
     * The text goes over first because the demo's handler only appends a message when the
     * draft is not empty, so an empty click would prove nothing: the batch would be empty
     * whether or not the handler ran.
     */
    @Test
    fun pr6_a_click_reaches_the_host_and_its_state_change_comes_back() {
        val connection = hostOrNull() ?: return
        val table = NodeTable()
        connection.init { table.apply(it) }

        val field = table.firstOfKind(WidgetKind.TextField)
            ?: fail("the demo tree has no TextField to type into")
        val button = table.firstOfKind(WidgetKind.Button)
            ?: fail("the demo tree has no Button to click")
        val onValueChange = field.handler(PropertyKind.OnValueChange)
            ?: fail("the TextField has no value handler")
        val onClick = button.handler(PropertyKind.OnClick)
            ?: fail("the Button has no click handler")

        val message = "typed in a browser"
        connection.dispatchEvent(HostEvent.TextChanged(field.id, onValueChange, message)) {
            table.apply(it)
        }
        connection.dispatchEvent(HostEvent.Clicked(button.id, onClick)) { table.apply(it) }

        val texts = table.allNodes()
            .filter { it.widget == WidgetKind.Text }
            .map { it.text(PropertyKind.Text) }
        assertTrue(
            texts.contains(message),
            "the handler's state change did not come back; the tree says $texts",
        )
        assertTrue(table.drainErrors().isEmpty(), "the reply batches decoded with errors")
        connection.shutdown()
    }

    /**
     * What a boundary call costs, measured rather than assumed.
     *
     * `ReleaseBatch` is the call to time: it is a real boundary function that does almost
     * nothing beyond the crossing, so what is left is the crossing. The baseline beside it
     * is the same loop calling a function in this module, which is what the crossing is
     * being compared against.
     *
     * The assertion is loose on purpose. The number is the point and it is printed; a tight
     * bound on a shared machine would fail for reasons that have nothing to do with the
     * boundary.
     */
    @Test
    fun pr6_the_forwarder_call_cost_is_measured_and_recorded() {
        val connection = hostOrNull() ?: return
        val table = NodeTable()
        connection.init { table.apply(it) }

        val out = connection.outAddressForMeasurement
        // Long enough that the engine has optimised the loop before the timed run.
        repeat(WARMUP) { hostReleaseBatch(out) }
        repeat(WARMUP) { localReleaseBatch(out) }

        val crossing = bestOf { runs -> repeat(runs) { hostReleaseBatch(out) } }
        val inModule = bestOf { runs -> repeat(runs) { localReleaseBatch(out) } }

        println(
            "pr6 forwarder cost: ${format(crossing)} ns/call across the boundary, " +
                "${format(inModule)} ns/call in this module, ${ITERATIONS} calls, " +
                "best of $ROUNDS, in ${engine()}",
        )
        assertTrue(
            crossing < CEILING_NANOS,
            "a boundary call cost ${format(crossing)} ns, over the ${CEILING_NANOS} ns " +
                "this test refuses to let pass unnoticed",
        )
        connection.shutdown()
    }

    /** The best of several timed runs, in nanoseconds per call. */
    private fun bestOf(run: (Int) -> Unit): Double {
        var best = Double.MAX_VALUE
        repeat(ROUNDS) {
            val started = now()
            run(ITERATIONS)
            val elapsed = now() - started
            val each = elapsed * 1_000_000.0 / ITERATIONS
            if (each < best) best = each
        }
        return best
    }

    /**
     * The same work as a boundary call, without leaving this module.
     *
     * It has to do something the compiler cannot drop, or the baseline measures an empty
     * loop rather than a call.
     */
    private fun localReleaseBatch(out: Int): Int {
        accumulator += out
        return accumulator and 1
    }

    private var accumulator = 0

    /** The Host, or null with a printed reason, because a page may be served without one. */
    private fun hostOrNull(): WebHostConnection? {
        // Mentioned so that this binary keeps it. In the application's module `main` is the
        // root of everything and the frame clock reaches this, so the export survives; a
        // test binary's roots are the test functions, and an export that nothing in the
        // tests names is dropped before it reaches the export section. The Host's frame
        // request would then have nothing to bind to and the instantiation would fail with
        // a link error about a function import that is not callable.
        onFrameRequested()
        if (compileHostForTest(HOST_WASM) == 0) {
            println(
                "pr6 skipped: no $HOST_WASM beside the test page. Run " +
                    "dioxus-compose-renderer/web/scripts/build-host.sh first.",
            )
            return null
        }
        return assertNotNull(
            WebHostConnection.install(),
            "the Host's module is here but it would not install",
        )
    }

    private fun format(nanos: Double): String {
        val hundredths = (nanos * 100).toLong()
        return "${hundredths / 100}.${(hundredths % 100).toString().padStart(2, '0')}"
    }

    private companion object {
        const val HOST_WASM = "./dioxus_compose_host.wasm"
        const val WARMUP = 200_000
        const val ITERATIONS = 2_000_000
        const val ROUNDS = 7
        const val CEILING_NANOS = 200.0
    }
}

/** Every node in the table, root first, in the order the tree walks. */
private fun NodeTable.allNodes(): List<Node> {
    val found = mutableListOf<Node>()
    val pending = ArrayDeque(roots)
    while (pending.isNotEmpty()) {
        val node = node(pending.removeFirst()) ?: continue
        found += node
        pending.addAll(node.children)
    }
    return found
}

private fun NodeTable.firstOfKind(kind: WidgetKind): Node? =
    allNodes().firstOrNull { it.widget == kind }

/**
 * Fetches and compiles the Host, and leaves it where the generated instantiation looks.
 *
 * Synchronous, because a `kotlin.test` test is. The page the toolchain generates for a test
 * run cannot load a module of its own, which is what would otherwise have done this before
 * the test started, so the fetch happens here and has to be finished by the time it returns.
 * Only this part is test-only: what the address goes on to do is the generated wiring.
 */
@JsFun(
    """(url) => {
  try {
    const request = new XMLHttpRequest();
    request.open('GET', url, false);
    // A synchronous request cannot ask for an ArrayBuffer, so the bytes come back as a
    // string whose character codes are the bytes, which is what this charset is for.
    request.overrideMimeType('text/plain; charset=x-user-defined');
    request.send(null);
    if (request.status !== 200) return 0;
    const text = request.responseText;
    const bytes = new Uint8Array(text.length);
    for (let index = 0; index < text.length; index++) {
      bytes[index] = text.charCodeAt(index) & 0xff;
    }
    globalThis.__dioxusComposeHostModule = new WebAssembly.Module(bytes);
    return 1;
  } catch (error) {
    console.info('dioxus-compose: could not compile the Host for the test: ' + error);
    return 0;
  }
}""",
)
private external fun compileHostForTest(url: String): Int

/** Milliseconds, as the page's own clock reports them. */
@JsFun("() => performance.now()")
private external fun now(): Double

/** Which engine the numbers were measured in, for the record they end up in. */
@JsFun("() => navigator.userAgent")
private external fun engine(): String
