//! Deterministic Kotlin protocol generation from the Rust schema.

use crate::protocol::{
    BatchEncoder, HostEvent, Mutation, PropertyValue, ProtocolError, encode_event,
};
use crate::schema::{
    EVENT_SCHEMA, EventPayloadType, FieldType, MODIFIER_SCHEMA, PROPERTY_SCHEMA, PROTOCOL_VERSION,
    PropertyKind, SCHEMA_HASH, Selection, WIDGET_SCHEMA, WidgetKind,
};
use crate::{EventPayload, Modifier};
use std::fmt::Write as _;

pub const GENERATED_RELATIVE_PATH: &str = concat!(
    "../dioxus-compose-renderer/native/generated/",
    "org/thisisthepy/dioxus/compose/protocol/Protocol.gen.kt"
);
pub const MUTATION_VECTOR_RELATIVE_PATH: &str = "tests/vectors/mutations.bin";
pub const EVENT_VECTOR_RELATIVE_PATH: &str = "tests/vectors/events.bin";
pub const VECTOR_DESCRIPTION_RELATIVE_PATH: &str = "tests/vectors/vectors.json";

pub fn generate_kotlin() -> String {
    let mut output = String::new();
    output
        .push_str("// Generated by `cargo run -p dioxus-compose --bin codegen`. DO NOT EDIT.\n\n");
    output.push_str("package org.thisisthepy.dioxus.compose.protocol\n\n");
    output.push_str("import java.nio.ByteBuffer\n");
    output.push_str("import java.nio.ByteOrder\n");
    output.push_str("import java.nio.charset.CodingErrorAction\n");
    output.push_str("import java.nio.charset.StandardCharsets\n\n");

    write_enum(&mut output, "WidgetKind", WIDGET_SCHEMA);
    write_enum(&mut output, "PropertyKind", PROPERTY_SCHEMA);

    output.push_str("sealed interface PropertyValue {\n");
    output.push_str("    data object None : PropertyValue\n");
    output.push_str("    data class Text(val value: String) : PropertyValue\n");
    output.push_str("    data class Bool(val value: Boolean) : PropertyValue\n");
    output.push_str("    data class Integer(val value: Long) : PropertyValue\n");
    output.push_str("    data class Float(val value: kotlin.Float) : PropertyValue\n");
    output.push_str("}\n\n");

    output.push_str("sealed interface Modifier {\n");
    for variant in MODIFIER_SCHEMA {
        if variant.fields.is_empty() {
            writeln!(output, "    data object {} : Modifier", variant.name).unwrap();
        } else {
            write!(output, "    data class {}(", variant.name).unwrap();
            for (index, field) in variant.fields.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                write!(output, "val {}: {}", field.name, kotlin_type(field.ty)).unwrap();
            }
            output.push_str(") : Modifier\n");
        }
    }
    output.push_str("}\n\n");

    output.push_str(
        r#"sealed interface Mutation {
    data class Create(val nodeId: Int, val widget: WidgetKind) : Mutation
    data class SetProp(val nodeId: Int, val property: PropertyKind, val value: PropertyValue) : Mutation
    data class SetModifier(val nodeId: Int, val index: Int, val modifier: Modifier) : Mutation
    data class Insert(val parentId: Int, val nodeId: Int, val index: Int) : Mutation
    data class Move(val parentId: Int, val nodeId: Int, val index: Int) : Mutation
    data class Remove(val nodeId: Int) : Mutation
    data class SetText(val nodeId: Int, val text: String, val selectionStart: Int, val selectionEnd: Int) : Mutation
}

"#,
    );

    output.push_str("sealed interface HostEvent {\n");
    output.push_str("    val nodeId: Int\n");
    output.push_str("    val handlerId: Long\n\n");
    for event in EVENT_SCHEMA {
        write!(
            output,
            "    data class {}(override val nodeId: Int, override val handlerId: Long",
            event.name
        )
        .unwrap();
        match event.payload {
            EventPayloadType::None => {}
            EventPayloadType::Text => output.push_str(", val text: String"),
            EventPayloadType::ProtocolError => {
                output.push_str(", val code: Int, val message: String");
            }
        }
        output.push_str(") : HostEvent\n");
    }
    output.push_str("}\n\n");

    output.push_str(
        r#"class ProtocolException(message: String, val offset: Int) :
    IllegalArgumentException("$message at byte offset $offset")

object Protocol {
"#,
    );
    writeln!(
        output,
        "    const val SCHEMA_HASH: Long = {}L",
        SCHEMA_HASH as i64
    )
    .unwrap();
    writeln!(
        output,
        "    const val PROTOCOL_VERSION: Int = {PROTOCOL_VERSION}"
    )
    .unwrap();
    output.push_str(
        r#"
    private const val TAG_ENVELOPE = 0
    private const val TAG_CREATE = 1
    private const val TAG_SET_PROP = 2
    private const val TAG_SET_MODIFIER = 3
    private const val TAG_INSERT = 4
    private const val TAG_MOVE = 5
    private const val TAG_REMOVE = 6
    private const val TAG_SET_TEXT = 7
    private const val ENVELOPE_LENGTH = 12

    private const val VALUE_NONE = 0
    private const val VALUE_TEXT = 1
    private const val VALUE_BOOL = 2
    private const val VALUE_INTEGER = 3
    private const val VALUE_FLOAT = 4

    /** Decodes a batch in place. Must not copy the buffer; only strings become Kotlin Strings. */
    fun decode(batch: ByteBuffer, onMutation: (Mutation) -> Unit) {
        val base = batch.position()
        val available = batch.remaining()
        val previousOrder = batch.order()
        batch.order(ByteOrder.LITTLE_ENDIAN)
        try {
            requireRange(available, 0, ENVELOPE_LENGTH, 0)
            if (readU16(batch, base, available, 0) != TAG_ENVELOPE ||
                readU16(batch, base, available, 2) != ENVELOPE_LENGTH
            ) {
                throw ProtocolException("invalid batch envelope", 0)
            }
            val recordsLengthLong = readU32(batch, base, available, 4)
            val countLong = readU32(batch, base, available, 8)
            if (recordsLengthLong < ENVELOPE_LENGTH ||
                recordsLengthLong > available.toLong() ||
                recordsLengthLong % 4L != 0L
            ) {
                throw ProtocolException("invalid records length", 4)
            }
            if (countLong > Int.MAX_VALUE.toLong()) {
                throw ProtocolException("record count is too large", 8)
            }
            val recordsLength = recordsLengthLong.toInt()
            val count = countLong.toInt()
            var offset = ENVELOPE_LENGTH
            var decoded = 0
            while (offset < recordsLength) {
                requireRange(recordsLength, offset, 4, offset)
                val tag = readU16(batch, base, available, offset)
                val length = readU16(batch, base, available, offset + 2)
                if (length < 4 || length % 4 != 0 || offset.toLong() + length > recordsLength) {
                    throw ProtocolException("invalid record length", offset + 2)
                }
                val mutation = when (tag) {
                    TAG_CREATE -> {
                        requireRecordLength(length, 12, offset)
                        Mutation.Create(
                            readU32(batch, base, available, offset + 4).toInt(),
                            widgetKind(readU16(batch, base, available, offset + 8), offset + 8),
                        )
                    }
                    TAG_SET_PROP -> {
                        requireRecordLength(length, 24, offset)
                        val value = when (val valueKind = readU16(batch, base, available, offset + 10)) {
                            VALUE_NONE -> PropertyValue.None
                            VALUE_TEXT -> PropertyValue.Text(readString(batch, base, available, offset + 12))
                            VALUE_BOOL -> PropertyValue.Bool(readU64(batch, base, available, offset + 12) != 0L)
                            VALUE_INTEGER -> PropertyValue.Integer(readU64(batch, base, available, offset + 12))
                            VALUE_FLOAT -> PropertyValue.Float(
                                kotlin.Float.fromBits(readU64(batch, base, available, offset + 12).toInt()),
                            )
                            else -> throw ProtocolException("unknown property value tag $valueKind", offset + 10)
                        }
                        Mutation.SetProp(
                            readU32(batch, base, available, offset + 4).toInt(),
                            propertyKind(readU16(batch, base, available, offset + 8), offset + 8),
                            value,
                        )
                    }
                    TAG_SET_MODIFIER -> {
                        requireRecordLength(length, 28, offset)
                        Mutation.SetModifier(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU16(batch, base, available, offset + 8),
                            modifier(
                                readU16(batch, base, available, offset + 10),
                                readU64(batch, base, available, offset + 12),
                                readU64(batch, base, available, offset + 20),
                                offset + 10,
                            ),
                        )
                    }
                    TAG_INSERT -> {
                        requireRecordLength(length, 16, offset)
                        Mutation.Insert(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU32(batch, base, available, offset + 8).toInt(),
                            readU32(batch, base, available, offset + 12).toInt(),
                        )
                    }
                    TAG_MOVE -> {
                        requireRecordLength(length, 16, offset)
                        Mutation.Move(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU32(batch, base, available, offset + 8).toInt(),
                            readU32(batch, base, available, offset + 12).toInt(),
                        )
                    }
                    TAG_REMOVE -> {
                        requireRecordLength(length, 8, offset)
                        Mutation.Remove(readU32(batch, base, available, offset + 4).toInt())
                    }
                    TAG_SET_TEXT -> {
                        requireRecordLength(length, 24, offset)
                        Mutation.SetText(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readString(batch, base, available, offset + 8),
                            readU32(batch, base, available, offset + 16).toInt(),
                            readU32(batch, base, available, offset + 20).toInt(),
                        )
                    }
                    else -> throw ProtocolException("unknown mutation tag $tag", offset)
                }
                onMutation(mutation)
                decoded += 1
                offset += length
            }
            if (offset != recordsLength || decoded != count) {
                throw ProtocolException("record count does not match envelope", offset)
            }
        } finally {
            batch.order(previousOrder)
        }
    }

    /** Encodes one event into `out` (little-endian), returns bytes written. */
    fun encodeEvent(event: HostEvent, out: ByteBuffer): Int {
        val start = out.position()
        val previousOrder = out.order()
        out.order(ByteOrder.LITTLE_ENDIAN)
        try {
            val text = when (event) {
"#,
    );
    for event in EVENT_SCHEMA {
        match event.payload {
            EventPayloadType::Text => {
                writeln!(
                    output,
                    "                is HostEvent.{} -> event.text.toByteArray(StandardCharsets.UTF_8)",
                    event.name
                )
                .unwrap();
            }
            EventPayloadType::ProtocolError => {
                writeln!(
                    output,
                    "                is HostEvent.{} -> event.message.toByteArray(StandardCharsets.UTF_8)",
                    event.name
                )
                .unwrap();
            }
            EventPayloadType::None => {
                writeln!(
                    output,
                    "                is HostEvent.{} -> null",
                    event.name
                )
                .unwrap();
            }
        }
    }
    output.push_str(
        r#"            }
            val recordLength = when (event) {
"#,
    );
    for event in EVENT_SCHEMA {
        let length = match event.payload {
            EventPayloadType::None => 16,
            EventPayloadType::Text => 24,
            EventPayloadType::ProtocolError => 28,
        };
        writeln!(
            output,
            "                is HostEvent.{} -> {length}",
            event.name
        )
        .unwrap();
    }
    output.push_str(
        r#"            }
            val totalLength = recordLength.toLong() + (text?.size ?: 0)
            if (totalLength > Int.MAX_VALUE || totalLength > out.remaining().toLong()) {
                throw ProtocolException("event output buffer is too small", 0)
            }
            val tag = when (event) {
"#,
    );
    for event in EVENT_SCHEMA {
        writeln!(
            output,
            "                is HostEvent.{} -> {}",
            event.name, event.tag
        )
        .unwrap();
    }
    output.push_str(
        r#"            }
            out.putShort(tag.toShort())
            out.putShort(recordLength.toShort())
            out.putInt(event.nodeId)
            out.putLong(event.handlerId)
            when (event) {
"#,
    );
    for event in EVENT_SCHEMA {
        match event.payload {
            EventPayloadType::None => {
                writeln!(
                    output,
                    "                is HostEvent.{} -> Unit",
                    event.name
                )
                .unwrap();
            }
            EventPayloadType::Text => {
                writeln!(
                    output,
                    "                is HostEvent.{} -> writeStringReference(out, recordLength, text!!)",
                    event.name
                )
                .unwrap();
            }
            EventPayloadType::ProtocolError => {
                writeln!(output, "                is HostEvent.{} -> {{", event.name).unwrap();
                output.push_str("                    out.putInt(event.code)\n");
                output.push_str(
                    "                    writeStringReference(out, recordLength, text!!)\n",
                );
                output.push_str("                }\n");
            }
        }
    }
    output.push_str(
        r#"            }
            if (text != null) out.put(text)
            return out.position() - start
        } finally {
            out.order(previousOrder)
        }
    }

    /** Handshake payload the Renderer sends to dioxus_compose_host_init. */
    fun handshake(out: ByteBuffer): Int {
        val start = out.position()
        if (out.remaining() < 12) {
            throw ProtocolException("handshake output buffer is too small", 0)
        }
        val previousOrder = out.order()
        out.order(ByteOrder.LITTLE_ENDIAN)
        try {
            out.putLong(SCHEMA_HASH)
            out.putShort(PROTOCOL_VERSION.toShort())
            out.put(0.toByte()) // LoopMode.Renderer
            out.put(0.toByte()) // Reserved for alignment.
            return out.position() - start
        } finally {
            out.order(previousOrder)
        }
    }

    private fun writeStringReference(out: ByteBuffer, offset: Int, bytes: ByteArray) {
        out.putInt(offset)
        out.putInt(bytes.size)
    }

    private fun widgetKind(tag: Int, offset: Int): WidgetKind = when (tag) {
"#,
    );
    for variant in WIDGET_SCHEMA {
        writeln!(
            output,
            "        {} -> WidgetKind.{}",
            variant.tag, variant.name
        )
        .unwrap();
    }
    output.push_str(
        r#"        else -> throw ProtocolException("unknown widget tag $tag", offset)
    }

    private fun propertyKind(tag: Int, offset: Int): PropertyKind = when (tag) {
"#,
    );
    for variant in PROPERTY_SCHEMA {
        writeln!(
            output,
            "        {} -> PropertyKind.{}",
            variant.tag, variant.name
        )
        .unwrap();
    }
    output.push_str(
        r#"        else -> throw ProtocolException("unknown property tag $tag", offset)
    }

    private fun modifier(tag: Int, first: Long, second: Long, offset: Int): Modifier = when (tag) {
"#,
    );
    for variant in MODIFIER_SCHEMA {
        write!(
            output,
            "        {} -> Modifier.{}",
            variant.tag, variant.name
        )
        .unwrap();
        if variant.fields.is_empty() {
            output.push('\n');
        } else {
            output.push('(');
            for (index, field) in variant.fields.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                let source = if index == 0 { "first" } else { "second" };
                output.push_str(modifier_decode_expression(field.ty, source));
            }
            output.push_str(")\n");
        }
    }
    output.push_str(
        r#"        else -> throw ProtocolException("unknown modifier tag $tag", offset)
    }

    private fun readString(batch: ByteBuffer, base: Int, available: Int, referenceOffset: Int): String {
        val offsetLong = readU32(batch, base, available, referenceOffset)
        val lengthLong = readU32(batch, base, available, referenceOffset + 4)
        if (offsetLong > Int.MAX_VALUE || lengthLong > Int.MAX_VALUE) {
            throw ProtocolException("string range is too large", referenceOffset)
        }
        val offset = offsetLong.toInt()
        val length = lengthLong.toInt()
        requireRange(available, offset, length, referenceOffset)
        val view = batch.duplicate()
        view.position(base + offset)
        view.limit(base + offset + length)
        return try {
            StandardCharsets.UTF_8.newDecoder()
                .onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT)
                .decode(view.slice())
                .toString()
        } catch (_: java.nio.charset.CharacterCodingException) {
            throw ProtocolException("string is not valid UTF-8", offset)
        }
    }

    private fun readU16(batch: ByteBuffer, base: Int, available: Int, offset: Int): Int {
        requireRange(available, offset, 2, offset)
        return batch.getShort(base + offset).toInt() and 0xffff
    }

    private fun readU32(batch: ByteBuffer, base: Int, available: Int, offset: Int): Long {
        requireRange(available, offset, 4, offset)
        return batch.getInt(base + offset).toLong() and 0xffff_ffffL
    }

    private fun readU64(batch: ByteBuffer, base: Int, available: Int, offset: Int): Long {
        requireRange(available, offset, 8, offset)
        return batch.getLong(base + offset)
    }

    private fun requireRecordLength(actual: Int, expected: Int, offset: Int) {
        if (actual != expected) {
            throw ProtocolException("invalid record length $actual for tag", offset + 2)
        }
    }

    private fun requireRange(available: Int, offset: Int, length: Int, errorOffset: Int) {
        if (offset < 0 || length < 0 || offset.toLong() + length > available.toLong()) {
            throw ProtocolException("truncated or out-of-range data", errorOffset)
        }
    }
}
"#,
    );
    output
}

pub fn generate_mutation_vector() -> Result<Vec<u8>, ProtocolError> {
    let mutations = [
        Mutation::Create {
            node_id: 1,
            widget: WidgetKind::Box,
        },
        Mutation::SetProp {
            node_id: 2,
            property: PropertyKind::Text,
            value: PropertyValue::String("안녕"),
        },
        Mutation::SetProp {
            node_id: 2,
            property: PropertyKind::Enabled,
            value: PropertyValue::Bool(true),
        },
        Mutation::SetProp {
            node_id: 2,
            property: PropertyKind::OnClick,
            value: PropertyValue::Integer(99),
        },
        Mutation::SetProp {
            node_id: 2,
            property: PropertyKind::Multiline,
            value: PropertyValue::Float(1.5),
        },
        Mutation::SetProp {
            node_id: 2,
            property: PropertyKind::Placeholder,
            value: PropertyValue::None,
        },
        Mutation::SetModifier {
            node_id: 1,
            index: 0,
            modifier: Modifier::Empty,
        },
        Mutation::SetModifier {
            node_id: 1,
            index: 1,
            modifier: Modifier::Padding(16.0),
        },
        Mutation::SetModifier {
            node_id: 1,
            index: 2,
            modifier: Modifier::FillMaxWidth,
        },
        Mutation::SetModifier {
            node_id: 1,
            index: 3,
            modifier: Modifier::FillMaxHeight,
        },
        Mutation::SetModifier {
            node_id: 1,
            index: 4,
            modifier: Modifier::Width(120.0),
        },
        Mutation::SetModifier {
            node_id: 1,
            index: 5,
            modifier: Modifier::Height(48.0),
        },
        Mutation::SetModifier {
            node_id: 1,
            index: 6,
            modifier: Modifier::Size {
                width: 20.0,
                height: 30.0,
            },
        },
        Mutation::SetModifier {
            node_id: 1,
            index: 7,
            modifier: Modifier::Background(0xff11_2233),
        },
        Mutation::SetModifier {
            node_id: 1,
            index: 8,
            modifier: Modifier::Clickable { handler_id: 42 },
        },
        Mutation::Insert {
            parent_id: 1,
            node_id: 2,
            index: 0,
        },
        Mutation::Move {
            parent_id: 1,
            node_id: 2,
            index: 1,
        },
        Mutation::Remove { node_id: 3 },
        Mutation::SetText {
            node_id: 4,
            text: "compose",
            selection: Some(Selection { start: 1, end: 4 }),
        },
    ];
    let mut encoder = BatchEncoder::default();
    for mutation in &mutations {
        encoder.encode(mutation)?;
    }
    Ok(encoder.finish()?.to_vec())
}

pub fn generate_event_vector() -> Result<Vec<u8>, ProtocolError> {
    let events = [
        HostEvent {
            node_id: 7,
            handler_id: 11,
            payload: EventPayload::Clicked,
        },
        HostEvent {
            node_id: 8,
            handler_id: 12,
            payload: EventPayload::TextChanged("한글"),
        },
        HostEvent {
            node_id: 8,
            handler_id: 13,
            payload: EventPayload::TextSubmitted("done"),
        },
        HostEvent {
            node_id: 8,
            handler_id: 14,
            payload: EventPayload::FocusLost,
        },
        HostEvent {
            node_id: 0,
            handler_id: 0,
            payload: EventPayload::ProtocolError {
                code: 9,
                message: "bad tag",
            },
        },
    ];
    let mut output = Vec::new();
    let mut encoded = Vec::new();
    for event in &events {
        encode_event(event, &mut encoded)?;
        output.extend_from_slice(&encoded);
    }
    Ok(output)
}

pub fn generate_vector_description() -> String {
    format!(
        r#"{{
  "format": "dioxus-compose protocol vectors v1",
  "schemaHashUnsigned": "{SCHEMA_HASH}",
  "byteOrder": "little-endian",
  "mutations": {{
    "file": "mutations.bin",
    "description": "One batch covering every M0 record, property value, and modifier layout",
    "recordCount": 19,
    "strings": ["안녕", "compose"]
  }},
  "events": {{
    "file": "events.bin",
    "description": "Five independently decodable event records concatenated in schema order",
    "records": [
      {{ "type": "Clicked", "offset": 0, "length": 16, "nodeId": 7, "handlerId": 11 }},
      {{ "type": "TextChanged", "offset": 16, "length": 30, "nodeId": 8, "handlerId": 12, "text": "한글" }},
      {{ "type": "TextSubmitted", "offset": 46, "length": 28, "nodeId": 8, "handlerId": 13, "text": "done" }},
      {{ "type": "FocusLost", "offset": 74, "length": 16, "nodeId": 8, "handlerId": 14 }},
      {{ "type": "ProtocolError", "offset": 90, "length": 35, "nodeId": 0, "handlerId": 0, "code": 9, "message": "bad tag" }}
    ]
  }}
}}
"#
    )
}

fn write_enum(output: &mut String, name: &str, variants: &[crate::schema::EnumVariantSchema]) {
    write!(output, "enum class {name} {{ ").unwrap();
    for (index, variant) in variants.iter().enumerate() {
        if index != 0 {
            output.push_str(", ");
        }
        output.push_str(variant.name);
    }
    output.push_str(" }\n\n");
}

fn kotlin_type(ty: FieldType) -> &'static str {
    match ty {
        FieldType::Float => "kotlin.Float",
        FieldType::U32 => "Int",
        FieldType::U64 => "Long",
    }
}

fn modifier_decode_expression(ty: FieldType, source: &str) -> &'static str {
    match (ty, source) {
        (FieldType::Float, "first") => "kotlin.Float.fromBits(first.toInt())",
        (FieldType::Float, "second") => "kotlin.Float.fromBits(second.toInt())",
        (FieldType::U32, "first") => "first.toInt()",
        (FieldType::U32, "second") => "second.toInt()",
        (FieldType::U64, "first") => "first",
        (FieldType::U64, "second") => "second",
        _ => unreachable!(),
    }
}
