// Extracts what fr34_box_tolerance.rs needs from the blitz-layout probe into small,
// committed files next to this script.
//
// Inputs, all inside this repository:
//   experiments/blitz-layout-probe/fixtures/{activitybar,sidebar,tabs}.html
//     the three workbench regions as static HTML, every element tagged with data-probe-id
//   experiments/blitz-layout-probe/captured/{activitybar,sidebar,tabs}.json
//     every element's rect and every text node's rects, read out of the running VS Code
//   experiments/blitz-layout-probe/captured/{activitybar,sidebar,tabs}.chrome-fixture.json
//     the same fixtures laid out by VS Code's Chromium, used to find the elements the static
//     fixture does not reproduce (compare.mjs excludes the same ones)
//   a Code-OSS checkout at commit 7debcd0e2acdea1c52de81bf9ee1620444407dda (MIT), and the
//   workbench stylesheet rebuilt from it by experiments/blitz-layout-probe/scripts/extract-css.mjs
//
// Outputs, in this directory:
//   workbench.css  the rules of the rebuilt stylesheet that can match an element of the three
//                  fixtures, in their original order
//   runtime-rebuilt.css
//                  the rules VS Code writes into the page at run time that can move a box in
//                  these regions, rebuilt from Code-OSS (see "Run-time stylesheet" below)
//   geometry.txt   per region, every element's live rect and whether the test compares it,
//                  and the text sizes VS Code measured
//
// usage (from the repository root, after the "Reproducing" steps of
// experiments/blitz-layout-probe/README.md have put Code-OSS under .scratch/):
//   node experiments/blitz-layout-probe/scripts/extract-css.mjs .scratch/blitz-layout-probe/vscode \
//     .scratch/blitz-layout-probe/out/workbench.css
//   node dioxus-compose/tests/fixtures/fr34/extract.mjs \
//     .scratch/blitz-layout-probe/vscode .scratch/blitz-layout-probe/out/workbench.css
//   node dioxus-compose/tests/fixtures/fr34/extract.mjs --report \
//     .scratch/blitz-layout-probe/vscode .scratch/blitz-layout-probe/out/workbench.css
//
// Run-time stylesheet. The probe also fed blitz-dom captured/runtime.css: every stylesheet
// the VS Code window had built in script. That file was copied out of the installed
// Microsoft build, is not committed and is not read here. What it carried that can move a
// box in these regions is generated by Code-OSS code, so this script generates the same
// from Code-OSS:
//   - codicon glyphs: src/vs/platform/theme/browser/iconsStyleSheet.ts writes
//     `.codicon-<id>:before { content: '<char>' }` for every registered icon. The workbench
//     stylesheet only sizes `.codicon` (codicon.css says "icon rules are dynamically created
//     by the platform theme service"), so without these rules no codicon has a ::before box.
//   - file icons: src/vs/workbench/services/themes/browser/fileIconThemeData.ts turns the
//     Seti icon theme (extensions/theme-seti/icons/vs-seti-icon-theme.json) into
//     `.show-file-icons ... .file-icon::before { content; font-family; font-size }`. Without
//     them the 16px icon box (plus its 6px padding) in front of every file label is missing.
//   - the sash size: src/vs/workbench/contrib/sash/browser/sash.ts writes
//     `--vscode-sash-size` and `--vscode-sash-hover-size` from the `workbench.sash.size`
//     setting (default 4 outside iOS, sash.contribution.ts). The sashes in the sidebar are
//     `height: var(--vscode-sash-size)`, so without it they have no height.
//   - theme colours: `--vscode-*` custom properties. A declaration such as
//     `border-left: 1px solid var(--vscode-x)` is invalid at computed-value time when the
//     property is undefined, and then has no border at all. `--report` lists every layout
//     declaration in a rule that can match the fixtures and depends on one. For these
//     regions they are the two sash properties above, outlines (which take no room), and a
//     border on the sticky-scroll container, which is `display: none` here.
// The theming participants (registerThemingParticipant) that write rules for these parts
// write colours, outlines, hover and high-contrast rules, and a tab border only for wrapped
// tabs; none of it moves a box in the dark theme with nothing hovered. The list styles sit
// in the fixtures themselves, as the <style> elements the regions contain.

import fs from 'node:fs';
import path from 'node:path';

const args = process.argv.slice(2);
const report = args[0] === '--report';
if (report) args.shift();
const [codeOss, workbenchCssPath] = args;
if (!codeOss || !workbenchCssPath) {
	console.error('usage: node extract.mjs [--report] <code-oss checkout> <rebuilt workbench.css>');
	process.exit(2);
}

const here = path.dirname(new URL(import.meta.url).pathname);
const repo = path.resolve(here, '../../../..');
const probe = path.join(repo, 'experiments/blitz-layout-probe');
const REGIONS = ['activitybar', 'sidebar', 'tabs'];

// ---------------------------------------------------------------------------------------
// HTML: the fixtures are outerHTML written by Chromium, so a plain tokenizer is enough.

const VOID = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr']);
const RAW = new Set(['style', 'script', 'textarea', 'title']);

function decodeEntities(s) {
	return s.replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi, (_, e) => {
		const l = e.toLowerCase();
		if (l[0] === '#') return String.fromCodePoint(l[1] === 'x' ? parseInt(l.slice(2), 16) : parseInt(l.slice(1), 10));
		return { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: '\u00a0' }[l];
	});
}

function parseHtml(html) {
	const root = { tag: '#document', attrs: {}, classes: [], children: [], parent: null, text: '' };
	let cur = root;
	let i = 0;
	const n = html.length;
	while (i < n) {
		if (html.startsWith('<!--', i)) {
			const end = html.indexOf('-->', i);
			i = end < 0 ? n : end + 3;
		} else if (html.startsWith('<!', i)) {
			i = html.indexOf('>', i) + 1;
		} else if (html.startsWith('</', i)) {
			const end = html.indexOf('>', i);
			const tag = html.slice(i + 2, end).trim().toLowerCase();
			let p = cur;
			while (p && p.tag !== tag) p = p.parent;
			if (p && p.parent) cur = p.parent;
			i = end + 1;
		} else if (html[i] === '<' && /[a-zA-Z]/.test(html[i + 1] || '')) {
			let j = i + 1;
			while (j < n && !/[\s/>]/.test(html[j])) j++;
			const tag = html.slice(i + 1, j).toLowerCase();
			const attrs = {};
			let selfClosing = false;
			while (j < n && html[j] !== '>') {
				if (/\s/.test(html[j])) { j++; continue; }
				if (html[j] === '/') { selfClosing = true; j++; continue; }
				let k = j;
				while (k < n && !/[\s=/>]/.test(html[k])) k++;
				const name = html.slice(j, k).toLowerCase();
				let value = '';
				j = k;
				if (html[j] === '=') {
					j++;
					const q = html[j];
					if (q === '"' || q === "'") {
						const end = html.indexOf(q, j + 1);
						value = html.slice(j + 1, end);
						j = end + 1;
					} else {
						let e = j;
						while (e < n && !/[\s>]/.test(html[e])) e++;
						value = html.slice(j, e);
						j = e;
					}
				}
				attrs[name] = decodeEntities(value);
			}
			const el = { tag, attrs, classes: (attrs.class || '').split(/\s+/).filter(Boolean), children: [], parent: cur, text: '' };
			cur.children.push(el);
			i = j + 1;
			if (RAW.has(tag)) {
				const end = html.toLowerCase().indexOf(`</${tag}`, i);
				el.text = html.slice(i, end);
				i = html.indexOf('>', end) + 1;
			} else if (!VOID.has(tag) && !selfClosing) {
				cur = el;
			}
		} else {
			const end = html.indexOf('<', i);
			const stop = end < 0 ? n : end;
			cur.text += decodeEntities(html.slice(i, stop));
			i = stop;
		}
	}
	return root;
}

function allElements(root) {
	const out = [];
	const walk = el => { for (const c of el.children) { out.push(c); walk(c); } };
	walk(root);
	return out;
}

// ---------------------------------------------------------------------------------------
// CSS: rules with their source text, nested blocks kept whole.

function skipString(css, i) {
	const q = css[i];
	i++;
	while (i < css.length && css[i] !== q) {
		if (css[i] === '\\') i++;
		i++;
	}
	return i + 1;
}

function stripCssComments(css) {
	let out = '';
	let i = 0;
	while (i < css.length) {
		if (css[i] === '/' && css[i + 1] === '*') {
			const end = css.indexOf('*/', i + 2);
			i = end < 0 ? css.length : end + 2;
		} else if (css[i] === '"' || css[i] === "'") {
			const e = skipString(css, i);
			out += css.slice(i, e);
			i = e;
		} else {
			out += css[i++];
		}
	}
	return out;
}

/** Index of the brace that closes the block opened at `open`. */
function blockEnd(css, open) {
	let depth = 0;
	for (let i = open; i < css.length; i++) {
		const c = css[i];
		if (c === '"' || c === "'") { i = skipString(css, i) - 1; continue; }
		if (c === '{') depth++;
		else if (c === '}') { depth--; if (depth === 0) return i; }
	}
	return css.length - 1;
}

/** Top-level rules: { kind: 'style'|'at', prelude, body, text }. */
function parseRules(css) {
	const rules = [];
	let i = 0;
	while (i < css.length) {
		while (i < css.length && /\s/.test(css[i])) i++;
		if (i >= css.length) break;
		if (css[i] === '}') { i++; continue; }
		// Find the end of the prelude: `{` or, for a statement at-rule, `;`.
		let j = i;
		while (j < css.length && css[j] !== '{' && css[j] !== ';' && css[j] !== '}') {
			if (css[j] === '"' || css[j] === "'") { j = skipString(css, j); continue; }
			if (css[j] === '(') { let d = 0; for (; j < css.length; j++) { if (css[j] === '(') d++; else if (css[j] === ')') { d--; if (d === 0) break; } } }
			j++;
		}
		const prelude = css.slice(i, j).trim();
		if (css[j] !== '{') {
			if (prelude) rules.push({ kind: 'at-statement', prelude, text: prelude + ';' });
			i = j + 1;
			continue;
		}
		const end = blockEnd(css, j);
		const body = css.slice(j + 1, end);
		rules.push({ kind: prelude.startsWith('@') ? 'at' : 'style', prelude, body, text: `${prelude} {${body}}` });
		i = end + 1;
	}
	return rules;
}

/** Splits on top-level commas (not inside parentheses, brackets or strings). */
function splitTopLevel(s, sep = ',') {
	const parts = [];
	let depth = 0;
	let start = 0;
	for (let i = 0; i < s.length; i++) {
		const c = s[i];
		if (c === '"' || c === "'") { i = skipString(s, i) - 1; continue; }
		if (c === '(' || c === '[') depth++;
		else if (c === ')' || c === ']') depth--;
		else if (c === sep && depth === 0) { parts.push(s.slice(start, i)); start = i + 1; }
	}
	parts.push(s.slice(start));
	return parts.map(p => p.trim()).filter(Boolean);
}

/** The declarations of a style rule body, nested rules left out. */
function declarations(body) {
	const out = [];
	let i = 0;
	let start = 0;
	let depth = 0;
	for (; i < body.length; i++) {
		const c = body[i];
		if (c === '"' || c === "'") { i = skipString(body, i) - 1; continue; }
		if (c === '(') depth++;
		else if (c === ')') depth--;
		else if (c === '{' && depth === 0) {
			const end = blockEnd(body, i);
			i = end;
			start = i + 1;
		} else if (c === ';' && depth === 0) {
			out.push(body.slice(start, i));
			start = i + 1;
		}
	}
	out.push(body.slice(start));
	return out
		.map(d => d.trim())
		.filter(d => d.includes(':') && !d.includes('{'))
		.map(d => { const k = d.indexOf(':'); return { prop: d.slice(0, k).trim().toLowerCase(), value: d.slice(k + 1).trim() }; });
}

// ---------------------------------------------------------------------------------------
// Selectors. The matcher is deliberately generous: anything it cannot decide (state
// pseudo-classes, :not, :has, structural pseudo-classes) counts as a match, so the kept rules
// are a superset of the rules that apply. Leaving in a rule that matches nothing changes no
// box; leaving out one that matches would.

function parseCompound(s) {
	const parts = { tag: null, ids: [], classes: [], attrs: [], pseudos: [] };
	let i = 0;
	const ident = () => {
		let j = i;
		while (j < s.length && (/[\w-]/.test(s[j]) || s[j] === '\\' || s.charCodeAt(j) > 127)) {
			if (s[j] === '\\') j++;
			j++;
		}
		const raw = s.slice(i, j);
		i = j;
		return raw.replace(/\\(.)/g, '$1');
	};
	while (i < s.length) {
		const c = s[i];
		if (c === '*') { i++; }
		else if (c === '&') { i++; parts.nesting = true; }
		else if (c === '#') { i++; parts.ids.push(ident()); }
		else if (c === '.') { i++; parts.classes.push(ident()); }
		else if (c === '[') {
			const end = s.indexOf(']', i);
			const inner = s.slice(i + 1, end).trim();
			const m = inner.match(/^([\w-]+)\s*(?:([~|^$*]?=)\s*(?:"([^"]*)"|'([^']*)'|([^\s\]]+))\s*(i)?)?$/);
			if (m) parts.attrs.push({ name: m[1].toLowerCase(), op: m[2] || null, value: m[3] ?? m[4] ?? m[5] ?? '', ci: !!m[6] });
			else parts.attrs.push({ unknown: true });
			i = end + 1;
		} else if (c === ':') {
			const element = s[i + 1] === ':';
			i += element ? 2 : 1;
			const name = ident().toLowerCase();
			let arg = null;
			if (s[i] === '(') {
				let d = 0;
				const st = i;
				for (; i < s.length; i++) { if (s[i] === '(') d++; else if (s[i] === ')') { d--; if (d === 0) break; } }
				arg = s.slice(st + 1, i);
				i++;
			}
			if (!element && !['before', 'after', 'first-line', 'first-letter', 'selection', 'placeholder', 'marker'].includes(name)) parts.pseudos.push({ name, arg });
			else parts.pseudoElement = name;
		} else if (/[\w-]/.test(c) || s.charCodeAt(i) > 127) {
			parts.tag = ident().toLowerCase();
		} else {
			i++;
		}
	}
	return parts;
}

/** A complex selector as compounds right to left, each with the combinator to its left. */
function parseComplex(sel) {
	const tokens = [];
	let buf = '';
	let depth = 0;
	let pendingComb = null;
	const flush = () => {
		if (buf.trim()) { tokens.push({ comb: pendingComb, compound: buf.trim() }); pendingComb = null; }
		buf = '';
	};
	for (let i = 0; i < sel.length; i++) {
		const c = sel[i];
		if (c === '"' || c === "'") { const e = skipString(sel, i); buf += sel.slice(i, e); i = e - 1; continue; }
		if (c === '(' || c === '[') depth++;
		if (c === ')' || c === ']') depth--;
		if (depth === 0 && (c === '>' || c === '+' || c === '~')) { flush(); pendingComb = c; continue; }
		if (depth === 0 && /\s/.test(c)) { flush(); if (!pendingComb && tokens.length) pendingComb = ' '; continue; }
		buf += c;
	}
	flush();
	// tokens[k].comb is the combinator between tokens[k-1] and tokens[k].
	return tokens.map(t => ({ comb: t.comb, parts: parseCompound(t.compound) }));
}

function attrMatches(el, a) {
	if (a.unknown) return true;
	if (!(a.name in el.attrs)) return false;
	if (!a.op) return true;
	let v = el.attrs[a.name];
	let want = a.value;
	if (a.ci) { v = v.toLowerCase(); want = want.toLowerCase(); }
	switch (a.op) {
		case '=': return v === want;
		case '~=': return v.split(/\s+/).includes(want);
		case '|=': return v === want || v.startsWith(want + '-');
		case '^=': return v.startsWith(want);
		case '$=': return v.endsWith(want);
		case '*=': return v.includes(want);
	}
	return true;
}

function compoundMatches(el, p) {
	if (p.tag && el.tag !== p.tag) return false;
	for (const id of p.ids) if (el.attrs.id !== id) return false;
	for (const c of p.classes) if (!el.classes.includes(c)) return false;
	for (const a of p.attrs) if (!attrMatches(el, a)) return false;
	for (const ps of p.pseudos) {
		if (ps.name === 'root' && el.tag !== 'html') return false;
		if ((ps.name === 'is' || ps.name === 'where' || ps.name === 'matches' || ps.name === '-webkit-any') && ps.arg) {
			if (!splitTopLevel(ps.arg).some(s => selectorMatches(el, s))) return false;
		}
		// Everything else (:not, :has, :hover, :focus, :first-child, :nth-child, ...) may match.
	}
	return true;
}

function matchFrom(el, compounds, k) {
	if (!compoundMatches(el, compounds[k].parts)) return false;
	if (k === 0) return true;
	const comb = compounds[k].comb || ' ';
	if (comb === '>') return !!el.parent && el.parent.tag !== '#document' && matchFrom(el.parent, compounds, k - 1);
	if (comb === ' ') {
		for (let p = el.parent; p && p.tag !== '#document'; p = p.parent) if (matchFrom(p, compounds, k - 1)) return true;
		return false;
	}
	const sibs = el.parent ? el.parent.children : [];
	const idx = sibs.indexOf(el);
	if (comb === '+') return idx > 0 && matchFrom(sibs[idx - 1], compounds, k - 1);
	for (let s = idx - 1; s >= 0; s--) if (matchFrom(sibs[s], compounds, k - 1)) return true;
	return false;
}

const complexCache = new Map();
function selectorMatches(el, sel) {
	let compounds = complexCache.get(sel);
	if (!compounds) { compounds = parseComplex(sel); complexCache.set(sel, compounds); }
	if (!compounds.length) return false;
	if (compounds.some(c => c.parts.nesting)) return true;
	return matchFrom(el, compounds, compounds.length - 1);
}

function ruleMatchesAny(prelude, elements) {
	return splitTopLevel(prelude).some(sel => elements.some(el => selectorMatches(el, sel)));
}

/** The rules that can apply to `elements`, with @media and @supports kept around them. */
function filterRules(rules, elements, out = []) {
	for (const r of rules) {
		if (r.kind === 'at-statement') { if (!/^@import/i.test(r.prelude)) out.push(r.text); continue; }
		if (r.kind === 'at') {
			const name = r.prelude.match(/^@([\w-]+)/)[1].toLowerCase();
			if (name === 'keyframes' || name === '-webkit-keyframes' || name === 'page') continue;
			if (name === 'font-face' || name === 'property' || name === 'counter-style') { out.push(r.text); continue; }
			const inner = filterRules(parseRules(r.body), elements, []);
			if (inner.length) out.push(`${r.prelude} {\n${inner.join('\n')}\n}`);
			continue;
		}
		if (ruleMatchesAny(r.prelude, elements)) out.push(r.text);
	}
	return out;
}

function compactCss(text) {
	return text
		.replace(/[ \t]*\n[ \t]*/g, '\n')
		.replace(/\n{2,}/g, '\n')
		.replace(/[ \t]{2,}/g, ' ')
		.trim();
}

// ---------------------------------------------------------------------------------------
// Code-OSS: codicon characters and the Seti file icon theme.

function readTree(dir, test, out = []) {
	for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
		const p = path.join(dir, ent.name);
		if (ent.isDirectory()) { if (ent.name !== 'test' && ent.name !== 'node_modules') readTree(p, test, out); }
		else if (test(p)) out.push(p);
	}
	return out;
}

/**
 * Every icon id Code-OSS registers, mapped to the id of the codicon it ends up drawing:
 * codiconsLibrary.ts registers the codicons with their characters, and `registerIcon(id,
 * Codicon.x, ...)` (and `register(id, ...)` in the library itself) make further ids that
 * point at one of them.
 */
function codiconTable(root) {
	const lib = fs.readFileSync(path.join(root, 'src/vs/base/common/codiconsLibrary.ts'), 'utf8');
	const chars = new Map();
	const keyToId = new Map();
	for (const m of lib.matchAll(/^\s*([\w$]+)\s*:\s*register\(\s*'([\w-]+)'\s*,\s*(0x[0-9a-f]+)\s*\)/gim)) {
		chars.set(m[2], parseInt(m[3], 16));
		keyToId.set(m[1], m[2]);
	}
	// Codicon.x may also come from codicons.ts (derived icons such as dialogError).
	const codicons = fs.readFileSync(path.join(root, 'src/vs/base/common/codicons.ts'), 'utf8');
	const aliases = new Map();
	for (const m of codicons.matchAll(/^\s*([\w$]+)\s*:\s*register\(\s*'([\w-]+)'\s*,\s*([^)]*)\)/gm)) {
		keyToId.set(m[1], m[2]);
		const v = m[3].trim();
		// register(id, 0xNNNN) or register(id, 'other-id') (codiconsUtil.ts).
		if (/^0x/i.test(v)) chars.set(m[2], parseInt(v, 16));
		else aliases.set(m[2], v.replace(/^['"]|['"]$/g, ''));
	}
	const resolveRef = ref => {
		const m = ref.match(/^Codicon\.([\w$]+)$/) || ref.match(/^codiconsLibrary\.([\w$]+)$/);
		return m ? keyToId.get(m[1]) : undefined;
	};

	// registerIcon(id, Codicon.x, ...) or registerIcon(id, someOtherRegisteredIcon, ...).
	const registered = new Map();
	const variables = new Map();
	const pending = [];
	const files = readTree(path.join(root, 'src/vs'), p => p.endsWith('.ts'));
	for (const f of files) {
		const text = fs.readFileSync(f, 'utf8');
		if (!text.includes('registerIcon(')) continue;
		for (const m of text.matchAll(/(?:(?:const|let|readonly)\s+([\w$]+)\s*(?::[^=]+)?=\s*)?registerIcon\(\s*'([\w-]+)'\s*,\s*([\w$.]+)/g)) {
			if (m[1]) variables.set(m[1], m[2]);
			const target = resolveRef(m[3]);
			if (target) registered.set(m[2], target);
			else pending.push([m[2], m[3]]);
		}
	}
	for (const [id, ref] of pending) {
		const target = variables.get(ref.split('.').pop());
		if (target && !registered.has(id)) registered.set(id, target);
	}
	const charOf = id => {
		for (let k = 0; k < 8 && id !== undefined; k++) {
			if (chars.has(id)) return chars.get(id);
			id = registered.get(id) ?? aliases.get(id);
		}
		return undefined;
	};
	return { charOf };
}

function readJsonc(file) {
	const text = fs.readFileSync(file, 'utf8')
		.replace(/\/\*[\s\S]*?\*\//g, '')
		.replace(/^\s*\/\/.*$/gm, '')
		.replace(/,(\s*[}\]])/g, '$1');
	return JSON.parse(text);
}

/** CSS class part as fileIconThemeData.ts writes it (classSelectorPart). */
function classSelectorPart(s) {
	return s.replace(/[\s]/g, '/').replace(/[.]/g, '\\.').replace(/[/]/g, '\\/');
}

/**
 * The Seti rules fileIconThemeData.ts would write, for the file-icon labels in the fixtures.
 * Folder icons are left out because the Seti theme defines none (which is why folder rows in
 * the capture have no ::before box).
 */
function setiRules(root, fileLabels) {
	const themeFile = path.join(root, 'extensions/theme-seti/icons/vs-seti-icon-theme.json');
	const theme = readJsonc(themeFile);
	const font = theme.fonts[0];
	const qualifier = '.show-file-icons';
	const rules = [];
	rules.push(`${qualifier} .file-icon::before, ${qualifier} .folder-icon::before, ${qualifier} .rootfolder-icon::before { font-family: '${font.id}'; font-size: ${font.size || '150%'}; }`);
	const def = id => theme.iconDefinitions[id] || {};
	const body = id => {
		const d = def(id);
		if (d.fontCharacter === undefined) return null;
		const ch = d.fontCharacter.replace(/^\\/, '');
		let s = `content: '\\${ch}';`;
		if (d.fontSize) s += ` font-size: ${d.fontSize};`;
		return s;
	};
	if (theme.file && body(theme.file)) rules.push(`${qualifier} .file-icon::before { ${body(theme.file)} }`);
	// For each label, the most specific association the theme has: file name, then
	// extension, then language, as fileIconThemeData.ts orders them by selector weight.
	const seen = new Set();
	for (const label of fileLabels) {
		const nameClass = label.classes.find(c => c.endsWith('-name-file-icon') && c !== 'name-file-icon');
		if (!nameClass) continue;
		const fileName = nameClass.slice(0, -'-name-file-icon'.length);
		const exts = label.classes.filter(c => c.endsWith('-ext-file-icon') && c !== 'ext-file-icon').map(c => c.slice(0, -'-ext-file-icon'.length));
		const lang = label.classes.find(c => c.endsWith('-lang-file-icon'))?.slice(0, -'-lang-file-icon'.length);
		const byName = theme.fileNames?.[fileName];
		const byExt = exts.sort((a, b) => b.length - a.length).map(e => [e, theme.fileExtensions?.[e]]).find(([, v]) => v);
		const byLang = lang && theme.languageIds?.[lang];
		let selector;
		let id;
		if (byName) {
			selector = `${qualifier} .${classSelectorPart(fileName)}-name-file-icon.name-file-icon.file-icon::before`;
			id = byName;
		} else if (byExt) {
			const segs = byExt[0].split('.');
			const parts = segs.map((_, i) => `.${classSelectorPart(segs.slice(i).join('.'))}-ext-file-icon`);
			selector = `${qualifier} ${parts.join('')}.ext-file-icon.file-icon::before`;
			id = byExt[1];
		} else if (byLang) {
			selector = `${qualifier} .${classSelectorPart(lang)}-lang-file-icon.file-icon::before`;
			id = byLang;
		}
		if (!selector || seen.has(selector) || !body(id)) continue;
		seen.add(selector);
		rules.push(`${selector} { ${body(id)} }`);
	}
	return { rules, fontId: font.id, fontSize: font.size };
}

// ---------------------------------------------------------------------------------------
// Captured geometry.

const SKIP_TAGS = new Set(['style', 'script', 'template', 'svg', 'path']);
const cap = (f) => JSON.parse(fs.readFileSync(path.join(probe, 'captured', f), 'utf8'));
const num = v => String(Math.round(v * 10000) / 10000);

function regionGeometry(name) {
	const live = cap(`${name}.json`);
	const fixture = new Map(cap(`${name}.chrome-fixture.json`).elements.map(e => [e.id, e]));
	const lines = [];
	let excluded = 0;
	for (const el of live.elements) {
		let status = 'compare';
		if (SKIP_TAGS.has(el.tag)) status = 'skip';
		else {
			const f = fixture.get(el.id);
			if (f && Math.max(Math.abs(f.x - el.x), Math.abs(f.y - el.y), Math.abs(f.w - el.w), Math.abs(f.h - el.h)) > 0.5) {
				status = 'excluded';
				excluded++;
			}
		}
		const cls = (el.cls || '').trim().split(/\s+/).filter(Boolean).slice(0, 3).join('.');
		lines.push(['el', el.id, status, num(el.x), num(el.y), num(el.w), num(el.h), `${el.tag}${cls ? '.' + cls : ''}`].join('\t'));
	}
	return { lines, excluded, live };
}

function px(v) {
	const m = /^([\d.]+)px$/.exec(v || '');
	return m ? Number(m[1]) : null;
}

// ---------------------------------------------------------------------------------------

const workbenchCss = stripCssComments(fs.readFileSync(workbenchCssPath, 'utf8'));
const workbenchRules = parseRules(workbenchCss);

const docs = Object.fromEntries(REGIONS.map(r => [r, parseHtml(fs.readFileSync(path.join(probe, 'fixtures', `${r}.html`), 'utf8'))]));
const elements = REGIONS.flatMap(r => allElements(docs[r]));

const keptWorkbench = filterRules(workbenchRules, elements);

const { charOf } = codiconTable(codeOss);
const codiconClasses = new Set();
for (const el of elements) {
	if (!el.classes.includes('codicon') && !el.classes.some(c => c.startsWith('codicon-'))) continue;
	for (const c of el.classes) if (c.startsWith('codicon-')) codiconClasses.add(c.slice('codicon-'.length));
}
const codiconRules = [];
const unknownCodicons = [];
for (const id of [...codiconClasses].sort()) {
	const ch = charOf(id);
	if (ch === undefined) { unknownCodicons.push(id); continue; }
	codiconRules.push(`.codicon-${id}:before { content: '\\${ch.toString(16)}'; }`);
}
const fileLabels = elements.filter(el => el.classes.includes('file-icon'));
const seti = setiRules(codeOss, fileLabels);

if (report) {
	// Declarations in kept rules that use a theme colour in a property that takes part in
	// layout: an undefined custom property makes the whole declaration invalid.
	const LAYOUT = /^(border|border-(top|right|bottom|left)|border-(top|right|bottom|left)-width|border-width|border-style|outline|outline-offset|padding.*|margin.*|width|height|min-.*|max-.*|font|font-size|font-family|font-weight|line-height|letter-spacing|display|flex.*|gap|row-gap|column-gap|top|left|right|bottom|inset|position|content|box-sizing|grid.*)$/;
	const hits = new Map();
	const walk = (rules) => {
		for (const r of rules) {
			if (r.kind === 'at') { const name = r.prelude.match(/^@([\w-]+)/)[1]; if (name !== 'font-face' && name !== 'keyframes') walk(parseRules(r.body)); continue; }
			if (r.kind !== 'style' || !ruleMatchesAny(r.prelude, elements)) continue;
			for (const d of declarations(r.body)) {
				if (!LAYOUT.test(d.prop) || !/var\(--vscode-/.test(d.value)) continue;
				const key = `${d.prop}: ${d.value}`;
				if (!hits.has(key)) hits.set(key, []);
				hits.get(key).push(r.prelude.replace(/\s+/g, ' ').slice(0, 140));
			}
		}
	};
	walk(workbenchRules);
	for (const r of REGIONS) {
		for (const el of allElements(docs[r])) if (el.tag === 'style') walk(parseRules(stripCssComments(el.text)));
	}

	// Every custom property a layout declaration of a kept rule reads, and whether anything
	// the test loads defines it: a kept rule, the rebuilt run-time rules, a fixture <style>
	// or an inline style attribute.
	const defined = new Set();
	const collectDefs = text => { for (const m of text.matchAll(/(--[\w-]+)\s*:/g)) defined.add(m[1]); };
	collectDefs(keptWorkbench.join('\n'));
	collectDefs('.monaco-workbench { --vscode-sash-size: 4px; --vscode-sash-hover-size: 4px; }');
	for (const el of elements) { if (el.attrs.style) collectDefs(el.attrs.style); if (el.tag === 'style') collectDefs(el.text); }
	const used = new Map();
	const walkVars = (rules) => {
		for (const r of rules) {
			if (r.kind === 'at') { const name = r.prelude.match(/^@([\w-]+)/)[1]; if (name !== 'font-face' && name !== 'keyframes') walkVars(parseRules(r.body)); continue; }
			if (r.kind !== 'style' || !ruleMatchesAny(r.prelude, elements)) continue;
			for (const d of declarations(r.body)) {
				if (!LAYOUT.test(d.prop) || d.prop.startsWith('outline')) continue;
				for (const m of d.value.matchAll(/var\(\s*(--[\w-]+)\s*(,)?/g)) {
					if (defined.has(m[1]) || m[2]) continue;
					if (!used.has(m[1])) used.set(m[1], new Set());
					used.get(m[1]).add(`${d.prop}: ${d.value}  in  ${r.prelude.replace(/\s+/g, ' ').slice(0, 120)}`);
				}
			}
		}
	};
	walkVars(workbenchRules);
	for (const el of elements) if (el.tag === 'style') walkVars(parseRules(stripCssComments(el.text)));
	console.log(`\ncustom properties read by layout declarations, without a fallback, that nothing defines (${used.size}):`);
	for (const [k, v] of used) console.log(`  ${k}\n    ${[...v].join('\n    ')}`);
	console.log(`kept ${keptWorkbench.length} of ${workbenchRules.length} top-level rules`);
	console.log(`codicon ids in the fixtures: ${codiconClasses.size}, without a character: ${unknownCodicons.join(', ') || 'none'}`);
	console.log(`seti rules: ${seti.rules.length}`);
	console.log(`\nlayout declarations that depend on a --vscode-* custom property (${hits.size}):`);
	for (const [k, v] of hits) console.log(`  ${k}\n      in ${v.length} rule(s), e.g. ${v[0]}`);
	process.exit(0);
}

const SOURCE_NOTE = [
	'Rebuilt from Code-OSS (https://github.com/microsoft/vscode) at commit',
	'7debcd0e2acdea1c52de81bf9ee1620444407dda.',
	'Copyright (c) Microsoft Corporation. Licensed under the MIT License.',
];

fs.writeFileSync(path.join(here, 'workbench.css'), [
	'/*',
	' * The rules of the VS Code workbench stylesheet that can match an element of the three',
	' * workbench fixtures in experiments/blitz-layout-probe/fixtures/, in their original order.',
	' * Source: the workbench.desktop.main.css that',
	' * experiments/blitz-layout-probe/scripts/extract-css.mjs rebuilds from Code-OSS.',
	' * Written by dioxus-compose/tests/fixtures/fr34/extract.mjs; do not edit by hand.',
	' *',
	...SOURCE_NOTE.map(l => ` * ${l}`),
	' */',
	compactCss(keptWorkbench.join('\n')),
	'',
].join('\n'));

fs.writeFileSync(path.join(here, 'runtime-rebuilt.css'), [
	'/*',
	' * The rules VS Code writes into the page at run time that can move a box in the three',
	' * workbench fixtures, rebuilt from the Code-OSS code that writes them:',
	' *   the sash size: src/vs/workbench/contrib/sash/browser/sash.ts, at the default setting;',
	' *   codicons: src/vs/platform/theme/browser/iconsStyleSheet.ts, with the characters from',
	' *     src/vs/base/common/codiconsLibrary.ts and the ids registered with registerIcon();',
	' *   file icons: src/vs/workbench/services/themes/browser/fileIconThemeData.ts over',
	' *     extensions/theme-seti/icons/vs-seti-icon-theme.json.',
	' * Only what sizes a box is written (`content`, `font-family`, `font-size`, the sash',
	' * lengths): colours do not move one. The icon fonts are not loaded; the test sizes their',
	' * glyphs itself.',
	' * Written by dioxus-compose/tests/fixtures/fr34/extract.mjs; do not edit by hand.',
	' *',
	...SOURCE_NOTE.map(l => ` * ${l}`),
	' */',
	'.monaco-workbench { --vscode-sash-size: 4px; --vscode-sash-hover-size: 4px; }',
	...codiconRules,
	...seti.rules,
	'',
].join('\n'));

// Text sizes. Every text node VS Code laid out, with the size of its one line as Chromium
// measured it, keyed by the font size and weight of the element it sits in.
const textRows = new Map();
const out = [
	'# What VS Code drew for the three workbench regions, for fr34_box_tolerance.rs.',
	'# Written by dioxus-compose/tests/fixtures/fr34/extract.mjs; do not edit by hand.',
	'# Sources: experiments/blitz-layout-probe/captured/{activitybar,sidebar,tabs}.json (rects read',
	'# from the running VS Code with getBoundingClientRect and Range.getClientRects) and',
	'# captured/{activitybar,sidebar,tabs}.chrome-fixture.json (the fixtures laid out by the same',
	'# Chromium, which decide the "excluded" elements, as compare.mjs does).',
	'# Window 1440 x 900 CSS px at device pixel ratio 1, so CSS px are device px.',
	'#',
	'# region <name> <elements excluded because the static fixture differs from the live window>',
	'# el     <data-probe-id> <compare|excluded|skip> <x> <y> <width> <height> <tag.classes>',
	'# text   <font-size> <font-weight> <width> <height> <ascent> <text>',
	'#   width and height are the text node\'s client rect: the advance Chromium shaped, and the',
	'#   font\'s content area (rounded ascent plus rounded descent), not the line box. Every one',
	'#   sits in an element with white-space nowrap or pre, so VS Code never wraps it. ascent is',
	'#   the part of the height above the baseline: Chromium rounds the ascent and the descent',
	'#   separately, and the font (.SF NS) has 1980 and 432 units of each in 2048, which the',
	'#   script checks against every height.',
	'# glyph  <font-family> <advance in em> <evidence>',
	'#   an icon font whose glyphs VS Code drew only as ::before content, which has no text node',
	'#   to measure; the advance comes from a box that holds nothing but one glyph.',
];
const glyphEvidence = new Map();
for (const r of REGIONS) {
	const { lines, excluded, live } = regionGeometry(r);
	out.push(`region\t${r}\t${excluded}`);
	out.push(...lines);
	const byId = new Map(live.elements.map(e => [e.id, e]));
	for (const t of live.texts) {
		if (!t.rects.length) continue;
		if (t.rects.length !== 1) throw new Error(`${r}: "${t.text}" took ${t.rects.length} lines in VS Code`);
		const p = byId.get(t.parent);
		const size = px(p.style['font-size']);
		const weight = Number(p.style['font-weight']);
		const key = `${t.text}\t${size}\t${weight}`;
		if (p.style['white-space'] !== 'nowrap' && p.style['white-space'] !== 'pre') {
			throw new Error(`${r}: "${t.text}" sits in white-space: ${p.style['white-space']}, so it could wrap`);
		}
		const ascent = Math.round(size * 1980 / 2048);
		const descent = Math.round(size * 432 / 2048);
		if (ascent + descent !== t.rects[0].h) throw new Error(`${r}: "${t.text}" is ${t.rects[0].h}px tall, not ${ascent} + ${descent}`);
		const row = ['text', size, weight, num(t.rects[0].w), num(t.rects[0].h), ascent, t.text].join('\t');
		const prev = textRows.get(key);
		if (prev && prev !== row) {
			const a = prev.split('\t')[3], b = num(t.rects[0].w);
			if (Math.abs(Number(a) - Number(b)) > 0.01) throw new Error(`"${t.text}" at ${size}px ${weight} measured ${a} and ${b}`);
		}
		textRows.set(key, row);
	}
	// A codicon box with no padding, no border and nothing in it but its ::before glyph:
	// its width is the glyph's advance.
	for (const el of live.elements) {
		const s = el.style;
		if (s['font-family'] !== 'codicon' || el.before === 'none' || el.w === 0) continue;
		if (s['padding-left'] !== '0px' || s['padding-top'] !== '0px' || s['margin-left'] !== '0px') continue;
		const fixtureEl = allElements(docs[r]).find(e => e.attrs['data-probe-id'] === String(el.id));
		if (!fixtureEl || fixtureEl.children.length || fixtureEl.text.trim()) continue;
		const size = px(s['font-size']);
		const em = el.w / size;
		const evidence = `${r} #${el.id} ${el.tag}.${el.cls.trim().split(/\s+/).join('.')} is ${num(el.w)} x ${num(el.h)} at ${size}px`;
		if (!glyphEvidence.has('codicon')) glyphEvidence.set('codicon', []);
		glyphEvidence.get('codicon').push({ em, evidence });
	}
}
for (const row of textRows.values()) out.push(row);
for (const [family, list] of glyphEvidence) {
	// A box with padding on the right (which the capture does not record) is wider than its
	// glyph; the narrowest box is the glyph itself.
	list.sort((a, b) => a.em - b.em);
	out.push(['glyph', family, num(list[0].em), list[0].evidence].join('\t'));
}
fs.writeFileSync(path.join(here, 'geometry.txt'), out.join('\n') + '\n');
console.log(`workbench.css: ${keptWorkbench.length} of ${workbenchRules.length} top-level rules`);
console.log(`runtime-rebuilt.css: ${codiconRules.length} codicon rules (${unknownCodicons.length} ids without a character: ${unknownCodicons.join(', ') || 'none'}), ${seti.rules.length} file icon rules`);
console.log(`geometry.txt: ${textRows.size} text sizes`);
