// Generated by `cargo run -p dioxus-compose --bin codegen`. DO NOT EDIT.

package org.thisisthepy.dioxus.compose.protocol

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets

enum class WidgetKind { Column, Row, Box, Text, TextField, Button, Spacer }

enum class PropertyKind { Text, Placeholder, Enabled, Multiline, OnClick, OnValueChange, OnSubmit, OnFocusLost, OnKeyDown }

enum class Key { Enter }

sealed interface PropertyValue {
    data object None : PropertyValue
    data class Text(val value: String) : PropertyValue
    data class Bool(val value: Boolean) : PropertyValue
    data class Integer(val value: Long) : PropertyValue
    data class Float(val value: kotlin.Float) : PropertyValue
}

sealed interface Modifier {
    data object Empty : Modifier
    data class Padding(val value: kotlin.Float) : Modifier
    data object FillMaxWidth : Modifier
    data object FillMaxHeight : Modifier
    data class Width(val value: kotlin.Float) : Modifier
    data class Height(val value: kotlin.Float) : Modifier
    data class Size(val width: kotlin.Float, val height: kotlin.Float) : Modifier
    data class Background(val argb: Int) : Modifier
    data class Clickable(val handlerId: Long) : Modifier
}

sealed interface Mutation {
    data class Create(val nodeId: Int, val widget: WidgetKind) : Mutation
    data class SetProp(val nodeId: Int, val property: PropertyKind, val value: PropertyValue) : Mutation
    data class SetModifier(val nodeId: Int, val index: Int, val modifier: Modifier) : Mutation
    data class Insert(val parentId: Int, val nodeId: Int, val index: Int) : Mutation
    data class Move(val parentId: Int, val nodeId: Int, val index: Int) : Mutation
    data class Remove(val nodeId: Int) : Mutation
    data class SetText(val nodeId: Int, val text: String, val selectionStart: Int, val selectionEnd: Int) : Mutation
    data class AppendText(val nodeId: Int, val text: String) : Mutation
}

sealed interface HostEvent {
    val nodeId: Int
    val handlerId: Long

    data class Clicked(override val nodeId: Int, override val handlerId: Long) : HostEvent
    data class TextChanged(override val nodeId: Int, override val handlerId: Long, val text: String) : HostEvent
    data class TextSubmitted(override val nodeId: Int, override val handlerId: Long, val text: String) : HostEvent
    data class FocusLost(override val nodeId: Int, override val handlerId: Long) : HostEvent
    data class ProtocolError(override val nodeId: Int, override val handlerId: Long, val code: Int, val message: String) : HostEvent
    data class KeyDown(override val nodeId: Int, override val handlerId: Long, val key: Key, val shiftKey: Boolean, val ctrlKey: Boolean, val altKey: Boolean, val metaKey: Boolean) : HostEvent
}

class ProtocolException(message: String, val offset: Int) :
    IllegalArgumentException("$message at byte offset $offset")

object Protocol {
    const val SCHEMA_HASH: Long = 6094773787085373026L
    const val PROTOCOL_VERSION: Int = 1

    private const val TAG_ENVELOPE = 0
    private const val TAG_CREATE = 1
    private const val TAG_SET_PROP = 2
    private const val TAG_SET_MODIFIER = 3
    private const val TAG_INSERT = 4
    private const val TAG_MOVE = 5
    private const val TAG_REMOVE = 6
    private const val TAG_SET_TEXT = 7
    private const val TAG_APPEND_TEXT = 8
    private const val ENVELOPE_LENGTH = 12

    private const val VALUE_NONE = 0
    private const val VALUE_TEXT = 1
    private const val VALUE_BOOL = 2
    private const val VALUE_INTEGER = 3
    private const val VALUE_FLOAT = 4

    /** Decodes a batch in place. Must not copy the buffer; only strings become Kotlin Strings. */
    fun decode(batch: ByteBuffer, onMutation: (Mutation) -> Unit) {
        val base = batch.position()
        val available = batch.remaining()
        val previousOrder = batch.order()
        batch.order(ByteOrder.LITTLE_ENDIAN)
        try {
            requireRange(available, 0, ENVELOPE_LENGTH, 0)
            if (readU16(batch, base, available, 0) != TAG_ENVELOPE ||
                readU16(batch, base, available, 2) != ENVELOPE_LENGTH
            ) {
                throw ProtocolException("invalid batch envelope", 0)
            }
            val recordsLengthLong = readU32(batch, base, available, 4)
            val countLong = readU32(batch, base, available, 8)
            if (recordsLengthLong < ENVELOPE_LENGTH ||
                recordsLengthLong > available.toLong() ||
                recordsLengthLong % 4L != 0L
            ) {
                throw ProtocolException("invalid records length", 4)
            }
            if (countLong > Int.MAX_VALUE.toLong()) {
                throw ProtocolException("record count is too large", 8)
            }
            val recordsLength = recordsLengthLong.toInt()
            val count = countLong.toInt()
            var offset = ENVELOPE_LENGTH
            var decoded = 0
            while (offset < recordsLength) {
                requireRange(recordsLength, offset, 4, offset)
                val tag = readU16(batch, base, available, offset)
                val length = readU16(batch, base, available, offset + 2)
                if (length < 4 || length % 4 != 0 || offset.toLong() + length > recordsLength) {
                    throw ProtocolException("invalid record length", offset + 2)
                }
                val mutation = when (tag) {
                    TAG_CREATE -> {
                        requireRecordLength(length, 12, offset)
                        Mutation.Create(
                            readU32(batch, base, available, offset + 4).toInt(),
                            widgetKind(readU16(batch, base, available, offset + 8), offset + 8),
                        )
                    }
                    TAG_SET_PROP -> {
                        requireRecordLength(length, 24, offset)
                        val value = when (val valueKind = readU16(batch, base, available, offset + 10)) {
                            VALUE_NONE -> PropertyValue.None
                            VALUE_TEXT -> PropertyValue.Text(readString(batch, base, available, offset + 12))
                            VALUE_BOOL -> PropertyValue.Bool(readU64(batch, base, available, offset + 12) != 0L)
                            VALUE_INTEGER -> PropertyValue.Integer(readU64(batch, base, available, offset + 12))
                            VALUE_FLOAT -> PropertyValue.Float(
                                kotlin.Float.fromBits(readU64(batch, base, available, offset + 12).toInt()),
                            )
                            else -> throw ProtocolException("unknown property value tag $valueKind", offset + 10)
                        }
                        Mutation.SetProp(
                            readU32(batch, base, available, offset + 4).toInt(),
                            propertyKind(readU16(batch, base, available, offset + 8), offset + 8),
                            value,
                        )
                    }
                    TAG_SET_MODIFIER -> {
                        requireRecordLength(length, 28, offset)
                        Mutation.SetModifier(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU16(batch, base, available, offset + 8),
                            modifier(
                                readU16(batch, base, available, offset + 10),
                                readU64(batch, base, available, offset + 12),
                                readU64(batch, base, available, offset + 20),
                                offset + 10,
                            ),
                        )
                    }
                    TAG_INSERT -> {
                        requireRecordLength(length, 16, offset)
                        Mutation.Insert(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU32(batch, base, available, offset + 8).toInt(),
                            readU32(batch, base, available, offset + 12).toInt(),
                        )
                    }
                    TAG_MOVE -> {
                        requireRecordLength(length, 16, offset)
                        Mutation.Move(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readU32(batch, base, available, offset + 8).toInt(),
                            readU32(batch, base, available, offset + 12).toInt(),
                        )
                    }
                    TAG_REMOVE -> {
                        requireRecordLength(length, 8, offset)
                        Mutation.Remove(readU32(batch, base, available, offset + 4).toInt())
                    }
                    TAG_SET_TEXT -> {
                        requireRecordLength(length, 24, offset)
                        Mutation.SetText(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readString(batch, base, available, offset + 8),
                            readU32(batch, base, available, offset + 16).toInt(),
                            readU32(batch, base, available, offset + 20).toInt(),
                        )
                    }
                    TAG_APPEND_TEXT -> {
                        requireRecordLength(length, 16, offset)
                        Mutation.AppendText(
                            readU32(batch, base, available, offset + 4).toInt(),
                            readString(batch, base, available, offset + 8),
                        )
                    }
                    else -> throw ProtocolException("unknown mutation tag $tag", offset)
                }
                onMutation(mutation)
                decoded += 1
                offset += length
            }
            if (offset != recordsLength || decoded != count) {
                throw ProtocolException("record count does not match envelope", offset)
            }
        } finally {
            batch.order(previousOrder)
        }
    }

    /** Encodes one event into `out` (little-endian), returns bytes written. */
    fun encodeEvent(event: HostEvent, out: ByteBuffer): Int {
        val start = out.position()
        val previousOrder = out.order()
        out.order(ByteOrder.LITTLE_ENDIAN)
        try {
            val text = when (event) {
                is HostEvent.Clicked -> null
                is HostEvent.TextChanged -> event.text.toByteArray(StandardCharsets.UTF_8)
                is HostEvent.TextSubmitted -> event.text.toByteArray(StandardCharsets.UTF_8)
                is HostEvent.FocusLost -> null
                is HostEvent.ProtocolError -> event.message.toByteArray(StandardCharsets.UTF_8)
                is HostEvent.KeyDown -> null
            }
            val recordLength = when (event) {
                is HostEvent.Clicked -> 16
                is HostEvent.TextChanged -> 24
                is HostEvent.TextSubmitted -> 24
                is HostEvent.FocusLost -> 16
                is HostEvent.ProtocolError -> 28
                is HostEvent.KeyDown -> 20
            }
            val totalLength = recordLength.toLong() + (text?.size ?: 0)
            if (totalLength > Int.MAX_VALUE || totalLength > out.remaining().toLong()) {
                throw ProtocolException("event output buffer is too small", 0)
            }
            val tag = when (event) {
                is HostEvent.Clicked -> 1
                is HostEvent.TextChanged -> 2
                is HostEvent.TextSubmitted -> 3
                is HostEvent.FocusLost -> 4
                is HostEvent.ProtocolError -> 5
                is HostEvent.KeyDown -> 6
            }
            out.putShort(tag.toShort())
            out.putShort(recordLength.toShort())
            out.putInt(event.nodeId)
            out.putLong(event.handlerId)
            when (event) {
                is HostEvent.Clicked -> Unit
                is HostEvent.TextChanged -> writeStringReference(out, recordLength, text!!)
                is HostEvent.TextSubmitted -> writeStringReference(out, recordLength, text!!)
                is HostEvent.FocusLost -> Unit
                is HostEvent.ProtocolError -> {
                    out.putInt(event.code)
                    writeStringReference(out, recordLength, text!!)
                }
                is HostEvent.KeyDown -> {
                    out.putShort(keyTag(event.key).toShort())
                    var modifiers = 0
                    if (event.shiftKey) modifiers = modifiers or 0x01
                    if (event.ctrlKey) modifiers = modifiers or 0x02
                    if (event.altKey) modifiers = modifiers or 0x04
                    if (event.metaKey) modifiers = modifiers or 0x08
                    out.put(modifiers.toByte())
                    out.put(0.toByte())
                }
            }
            if (text != null) out.put(text)
            return out.position() - start
        } finally {
            out.order(previousOrder)
        }
    }

    /** Handshake payload the Renderer sends to dioxus_compose_host_init. */
    fun handshake(out: ByteBuffer): Int {
        val start = out.position()
        if (out.remaining() < 12) {
            throw ProtocolException("handshake output buffer is too small", 0)
        }
        val previousOrder = out.order()
        out.order(ByteOrder.LITTLE_ENDIAN)
        try {
            out.putLong(SCHEMA_HASH)
            out.putShort(PROTOCOL_VERSION.toShort())
            out.put(0.toByte()) // LoopMode.Renderer
            out.put(0.toByte()) // Reserved for alignment.
            return out.position() - start
        } finally {
            out.order(previousOrder)
        }
    }

    private fun writeStringReference(out: ByteBuffer, offset: Int, bytes: ByteArray) {
        out.putInt(offset)
        out.putInt(bytes.size)
    }

    private fun widgetKind(tag: Int, offset: Int): WidgetKind = when (tag) {
        1 -> WidgetKind.Column
        2 -> WidgetKind.Row
        3 -> WidgetKind.Box
        4 -> WidgetKind.Text
        5 -> WidgetKind.TextField
        6 -> WidgetKind.Button
        7 -> WidgetKind.Spacer
        else -> throw ProtocolException("unknown widget tag $tag", offset)
    }

    private fun propertyKind(tag: Int, offset: Int): PropertyKind = when (tag) {
        1 -> PropertyKind.Text
        2 -> PropertyKind.Placeholder
        3 -> PropertyKind.Enabled
        4 -> PropertyKind.Multiline
        5 -> PropertyKind.OnClick
        6 -> PropertyKind.OnValueChange
        7 -> PropertyKind.OnSubmit
        8 -> PropertyKind.OnFocusLost
        9 -> PropertyKind.OnKeyDown
        else -> throw ProtocolException("unknown property tag $tag", offset)
    }

    private fun keyTag(key: Key): Int = when (key) {
        Key.Enter -> 1
    }

    private fun modifier(tag: Int, first: Long, second: Long, offset: Int): Modifier = when (tag) {
        0 -> Modifier.Empty
        1 -> Modifier.Padding(kotlin.Float.fromBits(first.toInt()))
        2 -> Modifier.FillMaxWidth
        3 -> Modifier.FillMaxHeight
        4 -> Modifier.Width(kotlin.Float.fromBits(first.toInt()))
        5 -> Modifier.Height(kotlin.Float.fromBits(first.toInt()))
        6 -> Modifier.Size(kotlin.Float.fromBits(first.toInt()), kotlin.Float.fromBits(second.toInt()))
        7 -> Modifier.Background(first.toInt())
        8 -> Modifier.Clickable(first)
        else -> throw ProtocolException("unknown modifier tag $tag", offset)
    }

    private fun readString(batch: ByteBuffer, base: Int, available: Int, referenceOffset: Int): String {
        val offsetLong = readU32(batch, base, available, referenceOffset)
        val lengthLong = readU32(batch, base, available, referenceOffset + 4)
        if (offsetLong > Int.MAX_VALUE || lengthLong > Int.MAX_VALUE) {
            throw ProtocolException("string range is too large", referenceOffset)
        }
        val offset = offsetLong.toInt()
        val length = lengthLong.toInt()
        requireRange(available, offset, length, referenceOffset)
        val view = batch.duplicate()
        view.position(base + offset)
        view.limit(base + offset + length)
        return try {
            StandardCharsets.UTF_8.newDecoder()
                .onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT)
                .decode(view.slice())
                .toString()
        } catch (_: java.nio.charset.CharacterCodingException) {
            throw ProtocolException("string is not valid UTF-8", offset)
        }
    }

    private fun readU16(batch: ByteBuffer, base: Int, available: Int, offset: Int): Int {
        requireRange(available, offset, 2, offset)
        return batch.getShort(base + offset).toInt() and 0xffff
    }

    private fun readU32(batch: ByteBuffer, base: Int, available: Int, offset: Int): Long {
        requireRange(available, offset, 4, offset)
        return batch.getInt(base + offset).toLong() and 0xffff_ffffL
    }

    private fun readU64(batch: ByteBuffer, base: Int, available: Int, offset: Int): Long {
        requireRange(available, offset, 8, offset)
        return batch.getLong(base + offset)
    }

    private fun requireRecordLength(actual: Int, expected: Int, offset: Int) {
        if (actual != expected) {
            throw ProtocolException("invalid record length $actual for tag", offset + 2)
        }
    }

    private fun requireRange(available: Int, offset: Int, length: Int, errorOffset: Int) {
        if (offset < 0 || length < 0 || offset.toLong() + length > available.toLong()) {
            throw ProtocolException("truncated or out-of-range data", errorOffset)
        }
    }
}
